const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('jplearnDesktop', {
  versions: {
    chrome: process.versions.chrome,
    electron: process.versions.electron,
    node: process.versions.node,
  },
  // ─ Setup wizard ──────────────────────────────────────────────────────
  isFirstRun: () => ipcRenderer.invoke('setup:is-first-run'),
  getSetupSystemInfo: () => ipcRenderer.invoke('setup:system-info'),
  downloadModel: (tier) => ipcRenderer.invoke('setup:download-model', tier),
  setActiveTutorModel: (tier) => ipcRenderer.invoke('setup:set-active-model', tier),
  uninstallTutorModel: (tier) => ipcRenderer.invoke('setup:uninstall-model', tier),
  downloadLlama: (backend) => ipcRenderer.invoke('setup:download-llama', backend),
  downloadOpenVoice: () => ipcRenderer.invoke('setup:download-openvoice'),
  completeSetup: () => ipcRenderer.invoke('setup:complete'),
  skipSetup: () => ipcRenderer.invoke('setup:skip'),
  onSetupProgress: (listener) => {
    const handler = (_event, data) => listener(data)
    ipcRenderer.on('setup:download-progress', handler)
    return () => ipcRenderer.removeListener('setup:download-progress', handler)
  },
  downloadFonts: () => ipcRenderer.invoke('setup:download-fonts'),
  downloadDictionary: () => ipcRenderer.invoke('setup:download-dictionary'),
  downloadSpeechModel: (tier) => ipcRenderer.invoke('setup:download-speech-model', tier),
  setActiveSpeechModel: (tier) => ipcRenderer.invoke('setup:set-active-speech-model', tier),
  uninstallSpeechModel: (tier) => ipcRenderer.invoke('setup:uninstall-speech-model', tier),
  createShortcuts: (opts) => ipcRenderer.invoke('setup:create-shortcuts', opts),
  getStudySummary: () => ipcRenderer.invoke('study:get-summary'),
  getBlockProgress: (slug) => ipcRenderer.invoke('study:get-block-progress', slug),
  getDeckCards: (slug) => ipcRenderer.invoke('study:get-deck-cards', slug),
  getStudyQueue: (slug) => ipcRenderer.invoke('study:get-study-queue', slug),
  searchDictionary: (query) => ipcRenderer.invoke('study:search-dictionary', query),
  getOverviewCharacterMastery: () => ipcRenderer.invoke('study:get-overview-character-mastery'),
  recordGameResult: (payload) => ipcRenderer.invoke('study:record-game-result', payload),
  startSessionGoal: (payload) => ipcRenderer.invoke('study:start-session-goal', payload),
  getSessionSummary: (sessionId) => ipcRenderer.invoke('study:get-session-summary', sessionId),
  applyExpertiseLevel: (level) => ipcRenderer.invoke('study:apply-expertise-level', level),
  getAssistantSnapshot: (sessionId) => ipcRenderer.invoke('assistant:get-snapshot', sessionId),
  getAssistantEvents: (limit) => ipcRenderer.invoke('assistant:get-events', limit),
  consumeAssistantEvents: (eventIds) => ipcRenderer.invoke('assistant:consume-events', eventIds),
  trackAssistantEvent: (payload) => ipcRenderer.invoke('assistant:track-event', payload),
  appendAssistantChatTurn: (payload) => ipcRenderer.invoke('assistant:append-chat-turn', payload),
  getAssistantChatHistory: (limit) => ipcRenderer.invoke('assistant:get-chat-history', limit),
  getPreloadedAssistantChatHistory: () => ipcRenderer.invoke('assistant:get-chat-history-preloaded'),
  clearAssistantChatHistory: () => ipcRenderer.invoke('assistant:clear-chat-history'),
  getAssistantChatRuntimeStatus: () => ipcRenderer.invoke('assistant-chat:status'),
  preloadAssistantChatRuntime: () => ipcRenderer.invoke('assistant-chat:preload'),
  sendAssistantChatMessage: (payload) => ipcRenderer.invoke('assistant-chat:send-message', payload),
  unloadAssistantChatRuntime: () => ipcRenderer.invoke('assistant-chat:unload'),
  cancelAssistantChatInference: () => ipcRenderer.invoke('assistant-chat:cancel'),
  speakText: (payload) => ipcRenderer.invoke('audio:speak', payload),
  getVoiceStatus: () => ipcRenderer.invoke('audio:voice-status'),
  preloadVoice: (speaker) => ipcRenderer.invoke('audio:preload', speaker),
  transcribeSpeech: (payload) => ipcRenderer.invoke('audio:transcribe', payload),
  getSpeechStatus: () => ipcRenderer.invoke('audio:speech-status'),
  resetStudyDb: () => ipcRenderer.invoke('study:reset-db'),
  notifyStartupReady: (payload) => ipcRenderer.invoke('ui:startup-ready', payload),
  setStartupTheme: (theme) => ipcRenderer.invoke('ui:set-startup-theme', theme),
  getConfigValue: (key) => ipcRenderer.invoke('config:get', key),
  setConfigValue: (key, value) => ipcRenderer.invoke('config:set', { key, value }),
  reloadLocalFonts: () => ipcRenderer.invoke('ui:reload-local-fonts'),
  minimizeWindow: () => ipcRenderer.invoke('window:minimize'),
  toggleMaximizeWindow: () => ipcRenderer.invoke('window:toggle-maximize'),
  isWindowMaximized: () => ipcRenderer.invoke('window:is-maximized'),
  onWindowStateChanged: (listener) => {
    const handler = (_event, state) => listener(state)
    ipcRenderer.on('window:state-changed', handler)
    return () => ipcRenderer.removeListener('window:state-changed', handler)
  },
  closeWindow: () => ipcRenderer.invoke('window:close'),
  getProgressionState: () => ipcRenderer.invoke('progression:get-state'),
  getFeatureState: () => ipcRenderer.invoke('features:get-state'),
  getXpProgress: () => ipcRenderer.invoke('xp:get-progress'),
  getRecommendations: () => ipcRenderer.invoke('recommendations:get'),
  getTutorReactions: () => ipcRenderer.invoke('tutor:get-reactions'),
  dismissTutorReaction: (dedupKey) => ipcRenderer.invoke('tutor:dismiss-reaction', dedupKey),
  getJLPTReadiness: () => ipcRenderer.invoke('jlpt:get-readiness'),
  buildJLPTExamQueue: (level, mode, count) => ipcRenderer.invoke('jlpt:build-exam-queue', level, mode, count),
  saveJLPTExamResult: (payload) => ipcRenderer.invoke('jlpt:save-exam-result', payload),
  getJLPTExamHistory: (level, mode) => ipcRenderer.invoke('jlpt:get-exam-history', level, mode),
  getLearningPathStatus: () => ipcRenderer.invoke('learning-path:get-status'),
  setLearningPath: (pathId) => ipcRenderer.invoke('learning-path:set', pathId),
  completeOnboarding: (payload) => ipcRenderer.invoke('learning-path:complete-onboarding', payload),
  exportAnalyticsCSV: (type) => ipcRenderer.invoke('analytics:export-and-save-csv', type),
})
