"""Auto-generated external deck data. Do not edit by hand."""

# Generated from: data/external_sources/words_n5.csv
# Generated from: data/external_sources/words_n4.csv
# Generated from: data/external_sources/words_n3.csv
# Generated from: data/external_sources/words_n2.csv
# Generated from: data/external_sources/words_n1.csv
# Generated from: data/external_sources/conversational_n5.csv
# Generated from: data/external_sources/kanji_n5.csv
# Generated from: data/external_sources/kanji_n4.csv
# Generated from: data/external_sources/kanji_n3.csv
# Generated from: data/external_sources/kanji_n2.csv
# Generated from: data/external_sources/kanji_n1.csv

VOCAB_N5_EXTERNAL_DATA: list[tuple[str, str, str]] = [
    ('ひとつ', 'hitotsu', 'one (native count)'),
    ('ふたつ', 'futatsu', 'two (native count)'),
    ('みっつ', 'mittsu', 'three (native count)'),
    ('よっつ', 'yottsu', 'four (native count)'),
    ('いつつ', 'itsutsu', 'five (native count)'),
    ('いくつ', 'ikutsu', 'how many?'),
    ('きょう', 'kyou', 'today'),
    ('きのう', 'kinou', 'yesterday'),
    ('あした', 'ashita', 'tomorrow'),
    ('あさ', 'asa', 'morning'),
    ('ひる', 'hiru', 'noon, daytime'),
    ('よる', 'yoru', 'night, evening'),
    ('いま', 'ima', 'now'),
    ('まいにち', 'mainichi', 'every day'),
    ('まいあさ', 'maiasa', 'every morning'),
    ('ことし', 'kotoshi', 'this year'),
    ('らいねん', 'rainen', 'next year'),
    ('きょねん', 'kyonen', 'last year'),
    ('おとうさん', 'otousan', 'father (polite)'),
    ('おかあさん', 'okaasan', 'mother (polite)'),
    ('おにいさん', 'oniisan', 'older brother (polite)'),
    ('おねえさん', 'oneesan', 'older sister (polite)'),
    ('おとうと', 'otouto', 'younger brother'),
    ('いもうと', 'imouto', 'younger sister'),
    ('かぞく', 'kazoku', 'family'),
    ('ともだち', 'tomodachi', 'friend'),
    ('からだ', 'karada', 'body'),
    ('あたま', 'atama', 'head'),
    ('かお', 'kao', 'face'),
    ('はな', 'hana', 'nose'),
    ('かみ', 'kami', 'hair'),
    ('せ/せい', 'se/sei', 'height, stature'),
    ('ごはん', 'gohan', 'rice, meal'),
    ('みず', 'mizu', 'water'),
    ('おちゃ', 'ocha', 'green tea'),
    ('こうひー', 'koohii', 'coffee'),
    ('パン', 'pan', 'bread'),
    ('たまご', 'tamago', 'egg'),
    ('さかな', 'sakana', 'fish'),
    ('にく', 'niku', 'meat'),
    ('やさい', 'yasai', 'vegetables'),
    ('くだもの', 'kudamono', 'fruit'),
    ('のむ', 'nomu', 'to drink'),
    ('たべる', 'taberu', 'to eat'),
    ('つくる', 'tsukuru', 'to make, to cook'),
    ('がっこう', 'gakkou', 'school'),
    ('だいがく', 'daigaku', 'university'),
    ('せんせい', 'sensei', 'teacher'),
    ('がくせい', 'gakusei', 'student'),
    ('きょうしつ', 'kyoushitsu', 'classroom'),
    ('ほん', 'hon', 'book'),
    ('ノート', 'nooto', 'notebook'),
    ('えんぴつ', 'enpitsu', 'pencil'),
    ('かばん', 'kaban', 'bag'),
    ('よむ', 'yomu', 'to read'),
    ('かく', 'kaku', 'to write'),
    ('べんきょうする', 'benkyou suru', 'to study'),
    ('うち/いえ', 'uchi/ie', 'house, home'),
    ('へや', 'heya', 'room'),
    ('にわ', 'niwa', 'garden'),
    ('みせ', 'mise', 'shop, store'),
    ('えき', 'eki', 'train station'),
    ('びょういん', 'byouin', 'hospital'),
    ('こうえん', 'kouen', 'park'),
    ('としょかん', 'toshokan', 'library'),
    ('でんしゃ', 'densha', 'train'),
    ('バス', 'basu', 'bus'),
    ('じてんしゃ', 'jitensha', 'bicycle'),
    ('くるま', 'kuruma', 'car'),
    ('ひこうき', 'hikouki', 'airplane'),
    ('のる', 'noru', 'to ride, to get on'),
    ('おりる', 'oriru', 'to get off'),
    ('おおきい', 'ookii', 'big'),
    ('ちいさい', 'chiisai', 'small'),
    ('たかい', 'takai', 'expensive, tall'),
    ('やすい', 'yasui', 'cheap'),
    ('あたらしい', 'atarashii', 'new'),
    ('ふるい', 'furui', 'old (things)'),
    ('いい/よい', 'ii/yoi', 'good'),
    ('わるい', 'warui', 'bad'),
    ('おおい', 'ooi', 'many, much'),
    ('すくない', 'sukunai', 'few, little'),
    ('むずかしい', 'muzukashii', 'difficult'),
    ('やさしい', 'yasashii', 'easy, kind'),
    ('おもしろい', 'omoshiroi', 'interesting, fun'),
    ('つまらない', 'tsumaranai', 'boring'),
    ('あつい', 'atsui', 'hot'),
    ('さむい', 'samui', 'cold (weather)'),
    ('つめたい', 'tsumetai', 'cold (to touch/drink)'),
    ('みる', 'miru', 'to see, to watch'),
    ('きく', 'kiku', 'to hear, to listen, to ask'),
    ('いく', 'iku', 'to go'),
    ('くる', 'kuru', 'to come'),
    ('かえる', 'kaeru', 'to return home'),
    ('いる', 'iru', 'to be (animate)'),
    ('ある', 'aru', 'to be, to exist (inanimate)'),
    ('する', 'suru', 'to do'),
    ('おきる', 'okiru', 'to wake up, to get up'),
    ('ねる', 'neru', 'to sleep, to go to bed'),
    ('かう', 'kau', 'to buy'),
    ('うる', 'uru', 'to sell'),
    ('はなす', 'hanasu', 'to speak, to talk'),
    ('わかる', 'wakaru', 'to understand'),
    ('しる', 'shiru', 'to know'),
    ('もつ', 'motsu', 'to hold, to have'),
    ('あう', 'au', 'to meet'),
    ('まつ', 'matsu', 'to wait'),
    ('あそぶ', 'asobu', 'to play, to have fun'),
    ('はたらく', 'hataraku', 'to work'),
    ('ひと', 'hito', 'person'),
    ('こども', 'kodomo', 'child, children'),
    ('おとこのひと', 'otoko no hito', 'man'),
    ('おんなのひと', 'onna no hito', 'woman'),
    ('なまえ', 'namae', 'name'),
    ('くに', 'kuni', 'country'),
    ('ことば', 'kotoba', 'word, language'),
    ('にほんご', 'nihongo', 'Japanese language'),
    ('えいご', 'eigo', 'English language'),
    ('てんき', 'tenki', 'weather'),
    ('かぜ', 'kaze', 'wind'),
    ('あめ', 'ame', 'rain'),
    ('ゆき', 'yuki', 'snow'),
    ('そら', 'sora', 'sky'),
    ('うみ', 'umi', 'sea, ocean'),
    ('やま', 'yama', 'mountain'),
    ('かわ', 'kawa', 'river'),
    ('まち', 'machi', 'town, city'),
    ('とき', 'toki', 'time, moment'),
    ('もの', 'mono', 'thing (tangible)'),
    ('こと', 'koto', 'thing (abstract)'),
    ('ああ', 'aa', 'Ah!, Oh!'),
    ('会う', 'au', 'to meet, to see'),
    ('青', 'ao', 'blue'),
    ('青い', 'aoi', 'blue'),
    ('赤', 'aka', 'red'),
    ('赤い', 'akai', 'red'),
    ('明るい', 'akarui', 'bright (in reference to personality or weather); cheerful'),
    ('秋', 'aki', 'fall (season)'),
    ('開く', 'aku', 'to open, to become open'),
    ('開ける', 'akeru', 'to open (v.t.)'),
    ('上げる', 'ageru', 'to raise, to lift'),
    ('朝', 'asa', 'morning'),
    ('朝御飯', 'asagohan', 'breakfast'),
    ('明後日', 'asatte', 'day after tomorrow'),
    ('足; 脚', 'ashi', 'foot; leg'),
    ('明日', 'ashita', 'tomorrow'),
    ('あそこ', 'asoko', 'there, over there, that place'),
    ('遊ぶ', 'asobu', 'to play; to spend time pleasantly; to hang out'),
    ('暖かい', 'atatakai', 'warm'),
    ('頭', 'atama', 'head'),
    ('新しい', 'atarashii', 'new'),
    ('あちら', 'achira', 'this way (polite)'),
    ('暑い', 'atsui', 'hot (in reference to weather), warm'),
    ('熱い', 'atsui', 'hot (objects)'),
    ('厚い', 'atsui', 'kind, warm(hearted), thick, deep'),
    ('あっち', 'acchi', 'over there'),
    ('後', 'ato', 'afterwards (later); in the future; the rest; since then'),
    ('あなた', 'anata', 'you'),
    ('兄', 'ani', '(my) older brother (humble)'),
    ('姉', 'ane', '(my) older sister (humble)'),
    ('アパート', 'apaato', 'apartment (abbr.)'),
    ('あの', 'ano', 'that over there; like that, that way; um...'),
    ('浴びる', 'abiru', 'to bathe, to shower'),
    ('危ない', 'abunai', 'dangerous, critical'),
    ('甘い', 'amai', 'generous, sweet'),
    ('余り', 'amari', 'not very; surplus'),
    ('雨', 'ame', 'rain'),
    ('飴', 'ame', '(hard) candy'),
    ('洗う', 'arau', 'to wash'),
    ('在る', 'aru', 'to be, to have'),
    ('有る', 'aru', 'to be, to have'),
    ('歩く', 'aruku', 'to walk'),
    ('あれ', 'are', 'that one (over there)'),
    ('いい; よい', 'ii yoi', 'good'),
    ('いいえ', 'iie', 'no, not at all'),
    ('言う', 'iu', 'to say'),
    ('家', 'ie', 'house, home'),
    ('いかが', 'ikaga', 'how, in what way'),
    ('行く', 'iku yuku', 'to go'),
    ('いくら', 'ikura', 'how much, how many'),
    ('池', 'ike', 'pond'),
    ('医者', 'isha', 'doctor; physician'),
    ('椅子', 'isu', 'chair'),
    ('忙しい', 'isogashii', 'busy (people, days)'),
    ('痛い', 'itai', 'hurt; painful; sore'),
    ('一', 'ichi', 'one'),
    ('一日', 'ichinichi', 'one day (duration)'),
    ('一番', 'ichiban', 'best (most), first, number one'),
    ('いつ', 'itsu', 'when'),
    ('五日', 'itsuka', 'five days; fifth day of the month'),
    ('一緒', 'issho', 'together'),
    ('五つ', 'itsutsu', 'five things'),
    ('いつも', 'itsumo', 'always, usually, every time, never (with neg. verb)'),
    ('犬', 'inu', 'dog'),
    ('今', 'ima', 'now'),
    ('意味', 'imi', 'meaning, significance'),
    ('妹', 'imouto', 'younger sister (humble)'),
    ('嫌', 'iya', 'disagreeable, detestable, unpleasant'),
    ('入口', 'iriguchi', 'entrance'),
    ('居る', 'iru', '(humble) to be (animate), to exist'),
    ('要る', 'iru', 'to need'),
    ('入れる', 'ireru', 'to put in'),
    ('色', 'iro', 'color'),
    ('色々', 'iroiro', 'various'),
    ('上', 'ue', 'above (up, top, etc.), over, on top of'),
    ('後ろ', 'ushiro', 'back, behind, rear'),
    ('薄い', 'usui', 'thin, weak'),
    ('歌', 'uta', 'a song'),
    ('歌う', 'utau', 'to sing'),
    ('うち', 'uchi', 'home; house; my place'),
    ('生まれる', 'umareru', 'to be born'),
    ('海', 'umi', 'sea, beach'),
    ('売る', 'uru', 'to sell (v.t.)'),
    ('うるさい', 'urusai', 'noisy; annoying'),
    ('上着', 'uwagi', 'coat, jacket'),
    ('絵', 'e', 'a painting; a picture; a drawing'),
    ('映画', 'eiga', 'movie, film'),
    ('映画館', 'eigakan', 'movie theater, cinema'),
    ('英語', 'eigo', 'English (language)'),
    ('ええ', 'ee', 'yes'),
    ('駅', 'eki', 'station'),
    ('エレベーター', 'erebeetaa', 'elevator'),
    ('鉛筆', 'empitsu', 'pencil'),
    ('美味しい', 'oishii', 'delicious, tasty'),
    ('多い', 'ooi', 'many; there are a lot'),
    ('大きい', 'ookii', 'big, large'),
    ('大きな', 'ookina', 'big'),
    ('大勢', 'oozei', 'great number of people'),
    ('お母さん', 'okaasan', 'mother (formal)'),
    ('お菓子', 'okashi', 'confections, sweets, snack'),
    ('お金', 'okane', 'money'),
    ('起きる', 'okiru', 'to get up (e.g., from sleeping); to happen'),
    ('置く', 'oku', 'to put; to lay; to place'),
    ('奥さん', 'okusan', "(someone else's) wife (hon.)"),
    ('お酒', 'osake', 'sake; alcohol'),
    ('お皿', 'osara', 'plate, dish'),
    ('伯父; 叔父さん', 'ojisan', 'uncle, middle-aged man'),
    ('おじいさん', 'ojiisan', 'grandfather, male senior citizen'),
    ('教える', 'oshieru', 'to teach, to inform, to instruct'),
    ('押す', 'osu', 'to push, to press, to stamp (e.g., a passport)'),
    ('遅い', 'osoi', 'slow; (to be) late'),
    ('お茶', 'ocha', '(green) tea'),
    ('お手洗い', 'otearai', "toilet, restroom, bathroom (lit., a place to wash one's hands)"),
    ('お父さん', 'otousan', 'father (formal)'),
    ('弟', 'otouto', 'younger brother'),
    ('男', 'otoko', 'man, male'),
    ('男の子', 'otokonoko', 'boy'),
    ('一昨日', 'ototoi', 'the day before yesterday'),
    ('おととし', 'ototoshi', 'year before last'),
    ('大人', 'otona', 'adult'),
    ('お腹', 'onaka', 'stomach'),
    ('同じ', 'onaji', 'same, identical'),
    ('お兄さん', 'oniisan', "(someone else's) older brother (formal)"),
    ('お姉さん', 'oneesan', 'older sister (formal)'),
    ('伯母さん; 叔母さん', 'obasan', 'aunt'),
    ('おばあさん', 'obaasan', 'grandmother, female senior-citizen'),
    ('お風呂', 'ofuro', 'a bath'),
    ('お弁当', 'obentou', 'a boxed lunch'),
    ('覚える', 'oboeru', 'to learn, to commit to memory, to remember, to memorize'),
    ('おまわりさん', 'omawarisan', 'policeman (friendly term)'),
    ('重い', 'omoi', 'heavy; serious'),
    ('面白い', 'omoshiroi', 'interesting, amusing'),
    ('泳ぐ', 'oyogu', 'to swim'),
    ('降りる', 'oriru', 'to get off'),
    ('終る', 'owaru', 'to finish, to close'),
    ('音楽', 'ongaku', 'Music'),
    ('女', 'onna', 'woman, female'),
    ('女の子', 'onnanoko', 'girl'),
    ('外国', 'gaikoku', 'foreign country; abroad'),
    ('外国人', 'gaikokujin', 'foreigner'),
    ('会社', 'kaisha', 'company, corporation'),
    ('階段', 'kaidan', 'stairs'),
    ('買い物', 'kaimono', 'shopping'),
    ('買う', 'kau', 'to buy'),
    ('返す', 'kaesu', 'to return something'),
    ('帰る', 'kaeru', 'to go back, to go home, to return'),
    ('顔', 'kao', 'face (body part)'),
    ('かかる', 'kakaru', 'it takes (amount of time, money) (v.i.)'),
    ('鍵', 'kagi', 'a lock; a key'),
    ('書く', 'kaku', 'to write'),
    ('学生', 'gakusei', 'student'),
    ('掛ける', 'kakeru', 'to put on (e.g., glasses); to hang (e.g., on a wall)'),
    ('かける', 'kakeru', 'to dial/call (e.g., phone); to sit down'),
    ('傘', 'kasa', 'umbrella, parasol'),
    ('貸す', 'kasu', 'to lend'),
    ('風', 'kaze', 'wind, breeze'),
    ('風邪', 'kaze', 'cold, flu'),
    ('方', 'kata', '-- honorific form for 人 (ひと) --; way of doing'),
    ('家族', 'kazoku', 'family, members of a family'),
    ('片仮名', 'katakana', 'katakana'),
    ('学校', 'gakkou', 'a school'),
    ('カップ', 'kappu', 'cup'),
    ('家庭', 'katei', 'home; family'),
    ('角', 'kado', 'corner (e.g., desk, pavement)'),
    ('花瓶', 'kabin', '(flower) vase'),
    ('かぶる', 'kaburu', 'to wear, to put on (e.g., a hat on the head)'),
    ('紙', 'kami', 'paper'),
    ('カメラ', 'kamera', 'camera'),
    ('火曜日', 'kayoubi', 'Tuesday'),
    ('辛い', 'karai', 'hot and spicy; salty'),
    ('体', 'karada', 'body; health'),
    ('借りる', 'kariru', 'to borrow, to owe'),
    ('軽い', 'karui', 'light, non-serious, minor'),
    ('カレー', 'karee', 'curry (abbr. for curry and rice)'),
    ('カレンダー', 'karendaa', 'calendar'),
    ('川; 河', 'kawa', 'river'),
    ('可愛い', 'kawaii', 'cute, adorable'),
    ('漢字', 'kanji', 'kanji; Chinese character'),
    ('木', 'ki', 'tree, wood, timber'),
    ('黄色', 'kiiro', 'yellow'),
    ('黄色い', 'kiiroi', 'yellow'),
    ('消える', 'kieru', 'to vanish, to disappear'),
    ('聞く', 'kiku', 'to hear, to listen, to ask'),
    ('北', 'kita', 'north'),
    ('ギター', 'gitaa', 'guitar'),
    ('汚い', 'kitanai', 'dirty, unclean, filthy'),
    ('喫茶店', 'kissaten', 'café'),
    ('切手', 'kitte', 'postal (postage) stamps'),
    ('切符', 'kippu', 'a ticket'),
    ('昨日', 'kinou', 'yesterday'),
    ('九', 'kyuu', 'nine'),
    ('牛肉', 'gyuuniku', 'beef'),
    ('牛乳', 'gyuunyuu', 'milk'),
    ('今日', 'kyou', 'today, this day'),
    ('教室', 'kyoushitsu', 'classroom'),
    ('兄弟', 'kyoudai', 'siblings (humble), brothers and sisters'),
    ('去年', 'kyonen', 'last year'),
    ('嫌い', 'kirai', 'dislike'),
    ('切る', 'kiru', 'to cut; to hang up (a phone)'),
    ('着る', 'kiru', 'to put on (clothes above your waist); to wear'),
    ('綺麗', 'kirei', 'pretty, clean, tidy'),
    ('キロ; キログラム', 'kiro kiroguramu', '(abbr.) kilo (kilogram)'),
    ('キロ; キロメートル', 'kiro kiromeetoru', '(abbr.) kilo (kilometer)'),
    ('銀行', 'ginkou', 'bank'),
    ('金曜日', 'kinyoubi', 'Friday'),
    ('九', 'ku', 'nine'),
    ('薬', 'kusuri', 'medicine'),
    ('下さい', 'kudasai', '(with te-form verb) please do for me'),
    ('果物', 'kudamono', 'fruit'),
    ('口', 'kuchi', 'job opening; mouth'),
    ('靴', 'kutsu', 'shoes, footwear'),
    ('靴下', 'kutsushita', 'socks'),
    ('国', 'kuni', 'country; place of origin'),
    ('曇り', 'kumori', 'cloudiness, cloudy weather'),
    ('曇る', 'kumoru', 'to become cloudy, to become dim'),
    ('暗い', 'kurai', 'dark, gloomy'),
    ('クラス', 'kurasu', 'a class'),
    ('グラム', 'guramu', 'gram'),
    ('来る', 'kuru', 'to come'),
    ('車', 'kuruma', 'car, vehicle'),
    ('黒', 'kuro', 'black'),
    ('黒い', 'kuroi', 'black; dark'),
    ('警官', 'keikan', 'police officer'),
    ('今朝', 'kesa', 'this morning'),
    ('消す', 'kesu', 'to erase, to delete, to turn off power'),
    ('結構', 'kekkou', 'splendid; enough, tolerably'),
    ('結婚', 'kekkon (suru)', 'marriage (get married)'),
    ('月曜日', 'getsuyoubi', 'Monday'),
    ('玄関', 'genkan', 'entrance (to a house or a building)'),
    ('元気', 'genki', 'health(y), energetic'),
    ('五', 'go', 'five'),
    ('公園', 'kouen', 'a park'),
    ('交差点', 'kousaten', 'intersection'),
    ('紅茶', 'koucha', 'black tea'),
    ('交番', 'kouban', 'police box'),
    ('声', 'koe', 'voice'),
    ('コート', 'kooto', 'coat; court (e.g., tennis)'),
    ('コーヒー', 'koohii', 'coffee'),
    ('ここ', 'koko', 'here, this place'),
    ('午後', 'gogo', 'afternoon, P.M.'),
    ('九日', 'kokonoka', 'nine days; ninth day of the month'),
    ('九つ', 'kokonotsu', 'nine things'),
    ('午前', 'gozen', 'morning, A.M.'),
    ('答える', 'kotaeru', 'to answer, to reply'),
    ('こちら', 'kochira', 'this person (polite); this way (polite)'),
    ('こっち', 'kocchi', 'this person; this direction; this side'),
    ('コップ', 'koppu', 'a tumbler; a glass'),
    ('今年', 'kotoshi', 'this year'),
    ('言葉', 'kotoba', 'language; word(s); expression(s)'),
    ('子供', 'kodomo', 'child(ren)'),
    ('この', 'kono', 'this'),
    ('御飯', 'gohan', 'rice (cooked); meal'),
    ('コピーする', 'kopiisuru', 'to copy'),
    ('困る', 'komaru', 'to be bothered, to have difficulty'),
    ('これ', 'kore', 'this one'),
    ('今月', 'kongetsu', 'this month'),
    ('今週', 'konshuu', 'this week'),
    ('こんな', 'konna', 'such, like this'),
    ('今晩', 'komban', 'tonight, this evening'),
    ('さあ', 'saa', 'come now, well'),
    ('財布', 'saifu', 'wallet'),
    ('魚', 'sakana', 'fish'),
    ('先', 'saki', 'future; recent, previous'),
    ('咲く', 'saku', 'to bloom'),
    ('作文', 'sakubun', 'essay; composition'),
    ('差す', 'sasu', 'to raise (stretch out) hands, to raise (e.g., umbrella)'),
    ('雑誌', 'zasshi', 'magazine, journal'),
    ('砂糖', 'satou', 'sugar'),
    ('寒い', 'samui', 'cold (in reference to weather)'),
    ('さ来年', 'sarainen', 'year after next'),
    ('三', 'san', 'three'),
    ('散歩', 'sampo (suru)', 'walk, stroll'),
    ('四', 'shi', 'four'),
    ('塩', 'shio', 'salt'),
    ('しかし', 'shikashi', 'however; but'),
    ('時間', 'jikan', 'time'),
    ('仕事', 'shigoto', 'work, job, occupation, employment'),
    ('辞書', 'jisho', 'dictionary'),
    ('静か', 'shizuka', 'quiet, calm'),
    ('下', 'shita', 'under, below, beneath'),
    ('七', 'shichi', 'seven'),
    ('質問', 'shitsumon', 'question, inquiry'),
    ('自転車', 'jitensha', 'bicycle'),
    ('自動車', 'jidousha', 'automobile'),
    ('死ぬ', 'shinu', 'to die'),
    ('字引', 'jibiki', 'dictionary'),
    ('自分', 'jibun', 'myself, oneself'),
    ('閉まる', 'shimaru', 'to close, to be closed'),
    ('閉める', 'shimeru', 'to close, to shut'),
    ('締める', 'shimeru', 'to tie, to fasten, to tighten'),
    ('じゃ; じゃあ', 'ja jaa', 'well, well then'),
    ('写真', 'shashin', 'a picture; a photograph'),
    ('シャツ', 'shatsu', 'shirt'),
    ('シャワー', 'shawaa', 'shower'),
    ('十', 'juu', 'ten'),
    ('授業', 'jugyou', 'a class (of school)'),
    ('宿題', 'shukudai', 'homework'),
    ('上手', 'jouzu', 'be good at, skillful'),
    ('丈夫', 'joubu', 'strong, solid, durable'),
    ('醤油', 'shouyu', 'soy sauce'),
    ('食堂', 'shokudou', 'cafeteria, dining hall'),
    ('知る', 'shiru', 'to know, to understand'),
    ('白', 'shiro', 'white'),
    ('白い', 'shiroi', 'white'),
    ('新聞', 'shimbun', 'newspaper'),
    ('水曜日', 'suiyoubi', 'Wednesday'),
    ('吸う', 'suu', 'to breathe in, to suck'),
    ('スカート', 'sukaato', 'skirt'),
    ('好き', 'suki', 'liking, fondness, love'),
    ('少ない', 'sukunai', 'a little; a few'),
    ('すぐに', 'suguni', 'immediately, soon'),
    ('少し', 'sukoshi', 'little, few'),
    ('涼しい', 'suzushii', 'cool, refreshing (in reference to weather)'),
    ('ストーブ', 'sutoobu', 'heater (lit: stove)'),
    ('スプーン', 'supuun', 'spoon'),
    ('スポーツ', 'supootsu', 'sport(s)'),
    ('ズボン', 'zubon', 'trousers'),
    ('住む', 'sumu', 'to reside, to live in'),
    ('座る', 'suwaru', 'to sit'),
    ('背', 'sei', "(one's) height, stature"),
    ('生徒', 'seito', 'student; pupil'),
    ('セーター', 'seetaa', 'sweater'),
    ('石鹸', 'sekken', 'soap'),
    ('背広', 'sebiro', "men's suit"),
    ('狭い', 'semai', 'narrow; not spacious'),
    ('ゼロ', 'zero', 'zero'),
    ('千', 'sen', 'thousand'),
    ('先月', 'sengetsu', 'last month'),
    ('先週', 'senshuu', 'last week'),
    ('先生', 'sensei', 'teacher, professor; master; doctor'),
    ('洗濯', 'sentaku', 'washing, laundry'),
    ('全部', 'zembu', 'all, entire, whole'),
    ('そう; そうです', 'sou soudesu', 'yes; appears, to be the case'),
    ('掃除', 'souji (suru)', 'cleaning, sweeping'),
    ('そうして; そして', 'soushite soshite', 'and, like that'),
    ('そこ', 'soko', 'that place, there; bottom, sole'),
    ('そちら', 'sochira', 'over there'),
    ('そっち', 'socchi', 'over there'),
    ('外', 'soto', 'outside, exterior'),
    ('その', 'sono', 'that'),
    ('そば', 'soba', 'near, close, beside; Japanese traditional buckwheat noodle'),
    ('空', 'sora', 'sky'),
    ('それ', 'sore', 'that one'),
    ('それから', 'sorekara', 'and then, after that'),
    ('それでは', 'soredeha', 'in that situation, well then...'),
    ('大学', 'daigaku', 'college; university'),
    ('大使館', 'taishikan', 'embassy'),
    ('大丈夫', 'daijoubu', "It's ok (all right); No need to worry; Everything is under control"),
    ('大好き', 'daisuki', 'very like-able, like very much'),
    ('大切', 'taisetsu', 'important'),
    ('台所', 'daidokoro', 'kitchen'),
    ('大変', 'taihen', 'very; difficult, hard'),
    ('高い', 'takai', 'tall, high; expensive'),
    ('沢山', 'takusan', 'many, much'),
    ('タクシー', 'takushii', 'taxi'),
    ('出す', 'dasu', 'to take (something) out; to hand in (something)'),
    ('立つ', 'tatsu', 'to stand up'),
    ('たて', 'tate', 'length, height'),
    ('建物', 'tatemono', 'building'),
    ('楽しい', 'tanoshii', 'enjoyable, fun'),
    ('頼む', 'tanomu', 'to request, to ask (a favor)'),
    ('たばこ', 'tabako', 'tobacco, cigarettes'),
    ('多分', 'tabun', 'perhaps, probably, maybe'),
    ('食べ物', 'tabemono', 'food'),
    ('食べる', 'taberu', 'to eat'),
    ('卵', 'tamago', 'egg'),
    ('誰', 'dare', 'who'),
    ('誰か', 'dareka', 'someone'),
    ('誕生日', 'tanjoubi', 'birthday'),
    ('段々', 'dandan', 'gradually, by degrees'),
    ('小さい', 'chiisai', 'small, little'),
    ('小さな', 'chiisana', 'small, little'),
    ('近い', 'chikai', 'near, close by, short'),
    ('違う', 'chigau', 'to be different; to differ; wrong'),
    ('近く', 'chikaku', 'nearby; in the neighborhood'),
    ('地下鉄', 'chikatetsu', 'underground train, subway'),
    ('地図', 'chizu', 'a map'),
    ('父', 'chichi', '(my) father'),
    ('茶色', 'chairo', 'brown'),
    ('茶碗', 'chawan', 'rice bowl'),
    ('丁度', 'choudo', 'just, right, exactly'),
    ('ちょっと', 'chotto', 'a little, somewhat; just a little, somewhat'),
    ('一日', 'tsuitachi', 'one day; first day of the month'),
    ('使う', 'tsukau', 'to use'),
    ('疲れる', 'tsukareru', 'to get (become) tired; to become fatigued'),
    ('次', 'tsugi', 'next'),
    ('着く', 'tsuku', 'to arrive at, to reach'),
    ('机', 'tsukue', 'desk'),
    ('作る', 'tsukuru', 'to make, to create'),
    ('つける', 'tsukeru', 'to turn on (e.g., a light); to take'),
    ('勤める', 'tsutomeru', 'to work (for)'),
    ('冷たい', 'tsumetai', 'cold (things, people)'),
    ('強い', 'tsuyoi', 'strong, powerful'),
    ('手', 'te', 'hand'),
    ('テープ', 'teepu', 'tape'),
    ('テープレコーダー', 'teepurekoodaa', 'tape recorder'),
    ('テーブル', 'teeburu', 'table'),
    ('出かける', 'dekakeru', 'to go out; to depart'),
    ('手紙', 'tegami', 'letter'),
    ('できる', 'dekiru', 'to be able to (to accomplish)'),
    ('出口', 'deguchi', 'an exit'),
    ('テスト', 'tesuto', 'test'),
    ('では', 'deha', 'then, well, so'),
    ('デパート', 'depaato', '(abbr.) department store'),
    ('でも', 'demo', 'but, however'),
    ('出る', 'deru', 'to appear, to leave'),
    ('テレビ', 'terebi', 'television, TV'),
    ('天気', 'tenki', 'weather'),
    ('電気', 'denki', 'electricity, (electric) light'),
    ('電車', 'densha', 'electric train'),
    ('電話', 'denwa', 'a telephone'),
    ('戸', 'to', 'door (Japanese style)'),
    ('ドア', 'doa', 'door (Western style)'),
    ('トイレ', 'toire', 'bathroom; toilet'),
    ('どう', 'dou', 'how, in what way'),
    ('どうして', 'doushite', 'why, for what reason'),
    ('どうぞ', 'douzo', 'please, kindly, by all means'),
    ('動物', 'doubutsu', 'animal'),
    ('どうも', 'doumo', 'Thank you; somehow; no matter how hard one may try'),
    ('十', '(o) too', 'ten (~)'),
    ('遠い', 'tooi', 'far (away), distant'),
    ('十日', 'tooka', 'ten days; tenth day of the month'),
    ('時々', 'tokidoki', 'sometimes'),
    ('時計', 'tokei', 'a watch; a clock'),
    ('どこ', 'doko', 'where, what place'),
    ('所', 'tokoro', 'place'),
    ('年', 'toshi', 'year, age'),
    ('図書館', 'toshokan', 'library'),
    ('どちら', 'dochira', 'which (one) (way); where (polite)'),
    ('どっち', 'docchi', 'which one, which way'),
    ('とても', 'totemo', 'very (much), greatly, exceedingly'),
    ('どなた', 'donata', 'who'),
    ('隣', 'tonari', 'next to, next door to'),
    ('どの', 'dono', 'which'),
    ('飛ぶ', 'tobu', 'to fly, to hop'),
    ('止まる', 'tomaru', 'to come to a halt'),
    ('友達', 'tomodachi', 'friend'),
    ('土曜日', 'doyoubi', 'Saturday'),
    ('鳥', 'tori', 'chicken (lit., bird)'),
    ('鶏肉', 'toriniku', 'chicken meat'),
    ('取る', 'toru', 'to take (a class); to get (a grade)'),
    ('撮る', 'toru', 'to take (a photo), to make (a film)'),
    ('どれ', 'dore', 'which one'),
    ('どんな', 'donna', 'what, what kind of'),
    ('ない', 'nai', "there isn't, doesn't have"),
    ('ナイフ', 'naifu', 'knife'),
    ('中', 'naka', 'inside, middle, among'),
    ('長い', 'nagai', 'long, lengthy'),
    ('鳴く', 'naku', 'to make sound (animal)'),
    ('無くす', 'nakusu', 'to lose something'),
    ('なぜ', 'naze', 'why (same as どうして)'),
    ('夏', 'natsu', 'summer'),
    ('夏休み', 'natsuyasumi', 'summer vacation'),
    ('七つ', 'nanatsu', 'seven things'),
    ('何', 'nan nani', 'what'),
    ('七日', 'nanoka', 'seven days; seventh day (of the month)'),
    ('名前', 'namae', 'name'),
    ('習う', 'narau', 'to learn'),
    ('並ぶ', 'narabu', 'to line up, to stand in a line (v.i.)'),
    ('並べる', 'naraberu', 'to put (things) side by side; to line up'),
    ('なる', 'naru', 'to become'),
    ('二', 'ni', 'two'),
    ('にぎやか', 'nigiyaka', 'bustling, busy'),
    ('肉', 'niku', 'meat'),
    ('西', 'nishi', 'west'),
    ('日曜日', 'nichiyoubi', 'Sunday'),
    ('荷物', 'nimotsu', 'luggage; baggage'),
    ('ニュース', 'nyuusu', 'news'),
    ('庭', 'niwa', 'garden'),
    ('脱ぐ', 'nugu', 'to take off (clothes)'),
    ('温い', 'nurui', 'lukewarm'),
    ('ネクタイ', 'nekutai', 'tie, necktie'),
    ('猫', 'neko', 'cat'),
    ('寝る', 'neru', 'to sleep; to go to sleep; to go to bed'),
    ('登る', 'noboru', 'to climb'),
    ('飲み物', 'nomimono', 'drink, beverage'),
    ('飲む', 'nomu', 'to drink'),
    ('乗る', 'noru', 'to get on, to ride in, to board'),
    ('歯', 'ha', 'tooth'),
    ('パーティー', 'paateii', 'a party'),
    ('はい', 'hai', 'yes'),
    ('灰皿', 'haizara', 'ashtray'),
    ('入る', 'hairu', 'to enter, to contain, to hold'),
    ('葉書', 'hagaki', 'postcard'),
    ('はく', 'haku', 'to put on (items below your waist)'),
    ('箱', 'hako', 'box'),
    ('橋', 'hashi', 'bridge'),
    ('箸', 'hashi', 'chopsticks'),
    ('始まる', 'hajimaru', '(something) begins'),
    ('初め; 始め', 'hajime', 'beginning, start'),
    ('初めて', 'hajimete', 'for the first time'),
    ('走る', 'hashiru', 'to run'),
    ('バター', 'bataa', 'butter'),
    ('二十歳', 'hatachi', '20 years old'),
    ('働く', 'hataraku', 'to work'),
    ('八', 'hachi', 'eight'),
    ('二十日', 'hatsuka', 'twenty days, twentieth (day of the month)'),
    ('花', 'hana', 'flower'),
    ('鼻', 'hana', 'nose'),
    ('話', 'hanashi', 'talk (chat), story'),
    ('話す', 'hanasu', 'to speak'),
    ('母', 'haha', '(my) mother'),
    ('早い', 'hayai', 'early'),
    ('速い', 'hayai', 'fast, quick'),
    ('春', 'haru', 'spring'),
    ('貼る', 'haru', 'to post; to paste; to attach'),
    ('晴れ', 'hare', 'clear (sunny) weather'),
    ('晴れる', 'hareru', 'to be sunny'),
    ('半', 'han', 'half (e.g., にじはん | half-past two)'),
    ('晩', 'ban', 'evening'),
    ('ハンカチ', 'hankachi', 'handkerchief'),
    ('番号', 'bangou', 'number, series of digits'),
    ('晩御飯', 'bangohan', 'dinner, evening meal'),
    ('半分', 'hambun', 'half'),
    ('東', 'higashi', 'east'),
    ('引く', 'hiku', 'to pull, to draw; subtract'),
    ('弾く', 'hiku', 'to play (a string instrument or piano)'),
    ('低い', 'hikui', 'short, low'),
    ('飛行機', 'hikouki', 'airplane'),
    ('左', 'hidari', 'left hand side'),
]

VOCAB_N4_EXTERNAL_DATA: list[tuple[str, str, str]] = [
    ('踏む', 'fumu', 'to step on, to tread on'),
    ('~区', '~ku', '~ district, ~ ward, ~ borough'),
    ('すっと', 'sutto', 'straight, quickly'),
    ('盗む', 'nusumu', 'to steal; to rob'),
    ('大抵', 'taitei', 'generally, usually'),
    ('とうとう', 'toutou', 'finally, at last'),
    ('ガソリン', 'gasorin', 'gasoline, petrol'),
    ('鳴る', 'naru', 'to sound, to ring (v.i.)'),
    ('しっかり', 'shikkari', 'firmly, steady'),
    ('生きる', 'ikiru', 'to live'),
    ('苦い', 'nigai', 'bitter'),
    ('沸く', 'waku', 'to boil, to grow hot'),
    ('意見', 'iken', 'opinion, view, idea'),
    ('やはり; やっぱり', 'yahari yappari', 'as I thought, absolutely'),
    ('漫画', 'manga', 'comic (book), cartoon'),
    ('ステレオ', 'sutereo', 'stereo'),
    ('医学', 'igaku', 'medical science'),
    ('テキスト', 'tekisuto', 'text; text book'),
    ('~月', '~tsuki', 'month'),
    ('折る', 'oru', 'to snap, to break; to bend'),
    ('~会', '~kai', '~ meeting'),
    ('うかがう', 'ukagau', 'to ask'),
    ('聞こえる', 'kikoeru', 'to be heard, to be audible'),
    ('僕', 'boku', 'I (used by men towards those of equal or lower status)'),
    ('必ず', 'kanarazu', 'surely, certainly'),
    ('壊す', 'kowasu', 'to break, to break down'),
    ('怒る', 'okoru', 'to get angry; to scold angrily'),
    ('床屋', 'tokoya', "barber's (shop)"),
    ('オートバイ', 'ootobai', 'motorcycle (lit: auto-bi(ke))'),
    ('運動', 'undousuru', 'exercise'),
    ('止む', 'yamu', 'to cease, to stop'),
    ('もし', 'moshi', 'if'),
    ('表', 'omote', 'surface; front; outside'),
    ('大学生', 'daigakusei', 'college student, university student'),
    ('運転手', 'untenshu', 'driver (by occupation)'),
    ('予習', 'yoshuu', 'preparation of lessons (for class)'),
    ('心配', 'shimpaisuru', 'worry, concern'),
    ('別', 'betsu', 'distinction, different'),
    ('非常に', 'hijouni', 'extremely; very'),
    ('お宅', 'otaku', "(someone else's) house; home -- polite word for 家 (いえ) --"),
    ('柔らかい', 'yawarakai', 'soft (in reference to texture), tender'),
    ('拾う', 'hirou', 'to pick up (something), to find'),
    ('~ございます', '~gozaimasu', 'to be (polite), to exist'),
    ('気', 'ki', 'spirit, mood'),
    ('比べる', 'kuraberu', 'to compare'),
    ('ほとんど', 'hotondo', 'mostly, almost'),
    ('つもり', 'tsumori', 'intention, plan'),
    ('郊外', 'kougai', 'suburb, outskirts'),
    ('だめ', 'dame', 'useless, no good, hopeless'),
    ('売り場', 'uriba', 'place where things are sold'),
    ('正月', 'shougatsu', "New Year, New Year's Day"),
    ('規則', 'kisoku', 'rule, regulation'),
    ('うん', 'un', 'yes (informal), all right (ok)'),
    ('発音', 'hatsuon', 'pronunciation'),
    ('焼く', 'yaku', 'to bake, to grill'),
    ('屋上', 'okujou', 'rooftop'),
    ('失礼', 'shitsurei', 'discourtesy, impoliteness; Excuse me'),
    ('ごみ', 'gomi', 'trash, garbage'),
    ('アフリカ', 'afurika', 'Africa'),
    ('点', 'ten', 'mark, score, grade; point, dot'),
    ('一生懸命', 'isshoukemmei', 'very hard (as in "to work hard"), with utmost effort'),
    ('今度', 'kondo', 'now, this time, near future, one of these days, next time'),
    ('機会', 'kikai', 'chance, opportunity'),
    ('建てる', 'tateru', 'to build'),
    ('複雑', 'fukuzatsu', 'complexity, complication'),
    ('彼', 'kare', 'he, boyfriend'),
    ('いらっしゃる', 'irassharu', '-- honorific expression for いく, くる, and いる --'),
    ('布団', 'futon', 'futon'),
    ('大事', 'daiji', 'important, valuable, serious matter'),
    ('贈り物', 'okurimono', 'a gift; a present'),
    ('泥棒', 'dorobou', 'thief; burglar'),
    ('~製', '~sei', 'made in ~'),
    ('注意', 'chuui', 'caution, attention'),
    ('台風', 'taifuu', 'typhoon'),
    ('日', 'hi', 'sun, sunshine, day'),
    ('~軒', '~ken', 'counter for houses'),
    ('そう', 'sou', 'really, (is that) so; yes, right'),
    ('通る', 'tooru', 'to pass (by), to go through'),
    ('過ぎる', 'sugiru', 'to exceed, to go beyond'),
    ('レポート; リポート', 'repooto ripooto', 'report'),
    ('葉', 'ha', 'leaf'),
    ('必要', 'hitsuyou', 'necessary'),
    ('課長', 'kachou', 'section manager'),
    ('地震', 'jishin', 'earthquake'),
    ('すると', 'suruto', 'and, then'),
    ('止める', 'yameru', 'to end, to stop'),
    ('ガラス', 'garasu', 'glass, pane'),
    ('~学部', '~gakubu', 'department of a university'),
    ('厳しい', 'kibishii', 'hard; rigorous; strict'),
    ('エスカレーター', 'esukareetaa', 'escalator'),
    ('人口', 'jinkou', 'population'),
    ('月', 'tsuki', 'moon'),
    ('絹', 'kinu', 'silk'),
    ('ちっとも', 'chittomo', 'not at all (neg. verb)'),
    ('深い', 'fukai', 'deep, profound'),
    ('壊れる', 'kowareru', 'to be broken, to break'),
    ('揺れる', 'yureru', 'to shake, to sway'),
    ('落る', 'ochiru', 'to fall, to drop'),
    ('できるだけ', 'dekirudake', 'if at all possible, as much as possible'),
    ('悲しい', 'kanashii', 'sad, sorrowful'),
    ('中学校', 'chuugakkou', 'junior high school pupil'),
    ('ガス', 'gasu', 'gas'),
    ('祈る', 'inoru', 'to pray; to wish'),
    ('盛ん', 'sakan', 'prosperous, active, thriving'),
    ('アルバイト', 'arubaito', 'part-time job'),
    ('起こす', 'okosu', 'to wake (someone) up'),
    ('致す', 'itasu', '-- extra-modest expression for する --'),
    ('噛む', 'kamu', 'to bite, to chew'),
    ('赤ちゃん', 'akachan', 'baby, infant'),
    ('浅い', 'asai', 'shallow, superficial'),
    ('嘘', 'uso', 'lie'),
    ('小説', 'shousetsu', 'novel'),
    ('親', 'oya', 'a parent'),
    ('それに', 'soreni', 'moreover; besides'),
    ('西洋', 'seiyou', 'the West, Western countries'),
    ('思う', 'omou', 'to think, to feel'),
    ('パート (タイム)', 'paato (taimu)', 'part time (esp. female part time employees)'),
    ('時代', 'jidai', 'age, period, epoch, era'),
    ('申し上げる', 'moushiageru', '(humble)to say, to tell'),
    ('~式', '~shiki', '~ ceremony; ~ style'),
    ('出席', 'shussekisuru', 'attendance'),
    ('~家', '~ka', 'person who is specialized in ~'),
    ('迎える', 'mukaeru', 'to welcome; to meet; to greet'),
    ('触る', 'sawaru', 'to touch, to feel'),
    ('建て', '~date', '~ storied, separate housing'),
    ('社長', 'shachou', 'president of a company'),
    ('動物園', 'doubutsuen', 'zoo'),
    ('捕まえる', 'tsukamaeru', 'to catch, to arrest'),
    ('季節', 'kisetsu', 'season (in reference to weather)'),
    ('寄る', 'yoru', 'to stop by'),
    ('決まる', 'kimaru', 'to be set; fixed (v.i.)'),
    ('開く', 'hiraku', 'to open; to hold (an event)'),
    ('逃げる', 'nigeru', 'to escape, to run away'),
    ('だから', 'dakara', 'so; therefore'),
    ('残念', 'zannen', 'regret; regrettable'),
    ('畳', 'tatami', 'tatami mat (Japanese straw mat)'),
    ('丁寧', 'teinei', 'polite, courteous, careful'),
    ('地理', 'chiri', 'geography'),
    ('さっき', 'sakki', 'a little while ago'),
    ('怖い', 'kowai', 'scary, frightening'),
    ('包む', 'tsutsumu', 'to wrap, to cover'),
    ('なるべく', 'narubeku', 'if possible, as much as possible'),
    ('無理', 'muri', 'unreasonable, impossible'),
    ('サンドイッチ', 'sandoicchi', 'sandwich'),
    ('会議室', 'kaigishitsu', 'conference room'),
    ('品物', 'shinamono', 'goods'),
    ('人形', 'ningyou', 'doll, figure'),
    ('利用', 'riyou', 'use, utilization'),
    ('飾る', 'kazaru', 'to decorate, to adorn'),
    ('止める', 'tomeru', 'to stop (something)'),
    ('恥ずかしい', 'hazukashii', 'ashamed, embarrassed'),
    ('いくら~ても', 'ikura~temo', 'however much one may ~'),
    ('用事', 'youji', 'business to take care of; tasks; errands'),
    ('ビル', 'biru', '(abbr.) building'),
    ('けんかする', 'kenkasuru', 'quarrel'),
    ('頑張る', 'gambaru', "to try one's best, to try hard, to persist"),
    ('投げる', 'nageru', 'to pitch, to cast away'),
    ('故障', 'koshousuru', 'breakdown'),
    ('力', 'chikara', 'strength, power'),
    ('受ける', 'ukeru', 'to take (an examination, interview, etc.); to receive'),
    ('気分', 'kibun', 'feeling, mood'),
    ('間違える', 'machigaeru', 'to make a mistake'),
    ('そんな', 'sonna', 'such, like that, that sort of'),
    ('星', 'hoshi', 'star'),
    ('場合', 'baai', 'case, situation'),
    ('やっと', 'yatto', 'at last, finally'),
    ('足りる', 'tariru', 'to be sufficient; to be enough'),
    ('行う', 'okonau', 'to carry out; to conduct (typically used in written language)'),
    ('ぶどう', 'budou', 'grapes'),
    ('無くなる', 'nakunaru', 'to disappear, to get lost'),
    ('準備', 'jumbisuru', 'prepare'),
    ('世界', 'sekai', 'world'),
    ('住所', 'juusho', 'address; place of residence'),
    ('再来月', 'saraigetsu', 'the month after next'),
    ('林', 'hayashi', 'woods, forest'),
    ('倍', 'bai', 'double'),
    ('痩せる', 'yaseru', 'to lose weight'),
    ('線', 'sen', 'line, wire'),
    ('戦争', 'sensou', 'war'),
    ('決める', 'kimeru', 'to decide (v.t.)'),
    ('調べる', 'shiraberu', 'to check; to look up; to inquire; to search'),
    ('寝坊', 'nebou', 'sleeping in late'),
    ('パパ', 'papa', 'papa, daddy'),
    ('光る', 'hikaru', 'to shine, to glitter'),
    ('夫', 'otto', 'husband'),
    ('雲', 'kumo', 'cloud'),
    ('坂', 'saka', 'slope, hill'),
    ('~(て) しまう', '~(te) shimau', 'to end up ~'),
    ('飛行場', 'hikoujou', 'airport'),
    ('柔道', 'juudou', 'judo'),
    ('決して', 'kesshite', 'never'),
    ('事務所', 'jimusho', 'office'),
    ('連絡', 'renraku', 'communication, contact, connection'),
    ('小学校', 'shougakkou', 'elementary school'),
    ('客', 'kyaku', 'guest, customer'),
    ('昔', 'mukashi', 'old days; past'),
    ('美しい', 'utsukushii', 'beautiful, lovely'),
    ('捨てる', 'suteru', 'throw away (trash), dump, discard'),
    ('なさる', 'nasaru', '-- honorific expression for する --'),
    ('事', 'koto', 'thing(s), matter(s), fact'),
    ('どんどん', 'dondon', 'quickly and steadily; at a rapid pace'),
    ('試合', 'shiai', 'match, game, competition'),
    ('適当', 'tekitou', 'fitness, suitability'),
    ('素晴らしい', 'subarashii', 'wonderful; terrific'),
    ('美術館', 'bijutsukan', 'art gallery, art museum'),
    ('文法', 'bumpou', 'grammar'),
    ('終わり', 'owari', 'end'),
    ('壁', 'kabe', 'wall'),
    ('一度', 'ichido', 'once, one time'),
    ('お礼', 'orei', 'expression of gratitude; thanking; gift of appreciation; bow'),
    ('親切', 'shinsetsu', 'kindness'),
    ('知らせる', 'shiraseru', 'to notify'),
    ('歯医者', 'haisha', 'dentist'),
    ('熱心', 'nesshin', 'enthusiasm'),
    ('始める', 'hajimeru', 'to start, to begin'),
    ('もらう', 'morau', 'to receive'),
    ('泣く', 'naku', 'to cry'),
    ('治る', 'naoru', 'to get better; to recover from illness (v.i.)'),
    ('熱', 'netsu', 'fever, temperature'),
    ('お祭り', 'omatsuri', 'festival'),
    ('水道', 'suidou', 'water service, water line'),
    ('匂い', 'nioi', 'odor, smell'),
    ('ベル', 'beru', 'bell'),
    ('赤ん坊', 'akambou', 'baby'),
    ('おかしい', 'okashii', 'strange; odd; funny'),
    ('事故', 'jiko', 'accident'),
    ('変', 'hen', 'strange, odd'),
    ('辞典', 'jiten', 'encyclopedia, reference book'),
    ('残る', 'nokoru', 'to remain (v.i.), to be left'),
    ('立てる', 'tateru', 'to stand (something) up, to erect (something)'),
    ('くれる', 'kureru', 'to give, to do for'),
    ('~員', '~in', 'member of ~'),
    ('原因', 'genin', 'cause, origin, source'),
    ('驚く', 'odoroku', 'to be surprised, to be astonished'),
    ('いただく', 'ku', '-- extra-modest expression for たべる and のむ; humble expression for もらう --'),
    ('祖母', 'sobo', 'grandmother'),
    ('場所', 'basho', 'place, location'),
    ('答', 'kotae', 'answer, response'),
    ('もちろん', 'mochiron', 'certainly, of course'),
    ('漬ける', 'tsukeru', 'to soak, to moisten, to pickle'),
    ('受付', 'uketsuke', 'reception(ist) desk'),
    ('内', 'uchi', 'within, inside'),
    ('スクリーン', 'sukuriin', 'screen'),
    ('増える', 'fueru', 'to increase, to multiply'),
    ('または', 'mataha', 'or, otherwise'),
    ('けがする', 'kegasuru', 'injury (to animate object), hurt'),
    ('以下', 'ika', 'less than, below'),
    ('選ぶ', 'erabu', 'to choose; to select'),
    ('~ばかり', '~bakari', 'just did ~, only'),
    ('心', 'kokoro', 'heart, mind'),
    ('~だす', '~dasu', 'to start doing ~'),
    ('サラダ', 'sarada', 'salad'),
    ('届ける', 'todokeru', 'to deliver (v.t.)'),
    ('挨拶', 'aisatsusuru', 'greet(ing)'),
    ('景色', 'keshiki', 'scenery, landscape'),
    ('確か', 'tashika', 'if I remember correctly; certain, definite'),
    ('ステーキ', 'suteeki', 'steak'),
    ('食料品', 'shokuryouhin', 'foodstuff, groceries'),
    ('森', 'mori', 'forest'),
    ('以内', 'inai', 'within, less (no more) than'),
    ('予定', 'yotei', 'plans, arrangement, schedule'),
    ('オーバー', 'oobaa', 'overcoat; over, exceeding, exaggeration'),
    ('乾く', 'kawaku', 'to get dry'),
    ('石', 'ishi', 'stone'),
    ('思い出す', 'omoidasu', 'to recall, to remember'),
    ('踊る', 'odoru', 'to dance'),
    ('細かい', 'komakai', 'small; fine, minute'),
    ('塗る', 'nuru', 'to paint, to plaster'),
    ('ご主人', 'goshujin', '(your, her) husband'),
    ('珍しい', 'mezurashii', 'unusual, rare'),
    ('用', 'you', 'errand, task, business (to take care of)'),
    ('公務員', 'koumuin', 'government worker, public servant'),
    ('お嬢さん', 'ojousan', "(someone's) daughter (polite)"),
    ('用意', 'youi', 'preparation'),
    ('探す', 'sagasu', 'to search, to seek, to look for'),
    ('形', 'katachi', 'shape'),
    ('運転', 'untensuru', 'driving'),
    ('すっかり', 'sukkari', 'all, completely'),
    ('アナウンサー', 'anaunsaa', 'announcer'),
    ('お土産', 'omiyage', 'souvenir'),
    ('消しゴム', 'keshigomu', 'eraser'),
    ('旅館', 'ryokan', 'a Japanese inn'),
    ('海岸', 'kaigan', 'coast, seashore'),
    ('寂しい', 'sabishii', 'lonely, lonesome'),
    ('火', 'hi', 'fire'),
    ('育てる', 'sodateru', 'to raise (v.t.); to bring up'),
    ('味噌', 'miso', 'miso, bean paste'),
    ('お祝い', 'oiwai', 'congratulation, celebration'),
    ('乗り物', 'norimono', 'vehicle'),
    ('案内', 'annaisuru', 'information, guidance'),
    ('通う', 'kayou', 'to go back and forth; to commute'),
    ('連れる', 'tsureru', 'to lead, to take (a person)'),
    ('技術', 'gijutsu', 'technique, technology, skill'),
    ('小鳥', 'kotori', 'small bird'),
    ('下宿', 'geshuku', 'lodging, boarding house'),
    ('ジャム', 'jamu', 'jam'),
    ('招待', 'shoutaisuru', 'invitation'),
    ('鏡', 'kagami', 'mirror'),
    ('はず', 'hazu', 'it should be so'),
    ('法律', 'houritsu', 'law'),
    ('進む', 'susumu', 'to advance, to proceed'),
    ('楽む', 'tanoshimu', 'to enjoy'),
    ('貿易', 'boueki', 'trade'),
    ('反対', 'hantai', 'oppose, opposition, resistance'),
    ('おる', 'oru', '-- extra-modest expression for いる --'),
    ('申す', 'mousu', '-- extra-modest (humble) expression for 言う (いう) --'),
    ('試験', 'shiken', 'an exam'),
    ('真面目', 'majime', 'diligent, serious'),
    ('店員', 'tenin', 'clerk; shop-employee'),
    ('泊まる', 'tomaru', 'to stay (over night) (v.i.)'),
    ('よろしい', 'yoroshii', '(hon.) good, OK, all right'),
    ('今夜', 'konya', 'this evening, tonight'),
    ('おつり', 'otsuri', 'change; balance of money returned to the purchaser'),
    ('チェックする', 'chiekkusuru', 'check'),
    ('会話', 'kaiwa', 'conversation'),
    ('空気', 'kuuki', 'air, atmosphere'),
    ('交通', 'koutsuu', 'traffic, transportation'),
    ('ワープロ', 'waapuro', 'word processor'),
    ('喜ぶ', 'yorokobu', 'to rejoice, to be delighted, to be glad'),
    ('急行', 'kyuukou', 'express train or bus'),
    ('皆', 'mina', 'everyone'),
    ('味', 'aji', 'flavor, taste'),
    ('空港', 'kuukou', 'airport'),
    ('手袋', 'tebukuro', 'glove(s)'),
    ('校長', 'kouchou', 'principal, headmaster'),
    ('ごちそう', 'gochisou', 'feast, treating (someone)'),
    ('踊り', 'odori', 'dance'),
    ('興味', 'kyoumi', 'interest (in something)'),
    ('引っ越す', 'hikkosu', 'to move to a new place of residence'),
    ('冷房', 'reibou', 'cooling, air conditioning'),
    ('都合', 'tsugou', 'circumstances, convenience'),
    ('遠慮', 'enryosuru', 'restraint, reserve, hesitate'),
    ('亡くなる', 'nakunaru', 'to pass away'),
    ('科学', 'kagaku', 'science'),
    ('はっきり', 'hakkiri', 'clearly, distinctly'),
    ('差し上げる', 'sashiageru', '-- humble expression for あげる --'),
    ('気持ち', 'kimochi', 'feeling, sensation, mood'),
    ('祖父', 'sofu', 'grandfather'),
    ('港', 'minato', 'harbor, port'),
    ('予約', 'yoyaku', 'reservation'),
    ('凄い', 'sugoi', 'terrific, great'),
    ('入学', 'nyuugakusuru', 'entry to school or university'),
    ('片付ける', 'katazukeru', 'to (clean) tidy up (v.t.), to put away'),
    ('写す', 'utsusu', 'to copy (v.t.); to photograph'),
    ('パソコン', 'pasokon', '(personal) computer'),
    ('部長', 'buchou', 'department (division) manager'),
    ('火事', 'kaji', 'fire'),
    ('足す', 'tasu', 'to add (numbers)'),
    ('教会', 'kyoukai', 'church'),
    ('彼ら', 'karera', 'they (usually male)'),
    ('一杯', 'ippai', 'full, to the utmost'),
    ('アメリカ', 'amerika', 'America, U.S.A.'),
    ('男性', 'dansei', 'man; male'),
    ('理由', 'riyuu', 'reason'),
    ('生産', 'seisansuru', 'production; to produce'),
    ('着物', 'kimono', 'kimono; Japanese traditional dress'),
    ('おもちゃ', 'omocha', 'a toy'),
    ('暮れる', 'kureru', 'to get dark, to come to an end'),
    ('釣る', 'tsuru', 'to fish'),
    ('~ちゃん', '~chan', 'suffix for familiar (female) person'),
    ('打つ', 'utsu', 'to hit, to strike'),
    ('あんな', 'anna', 'such, like that'),
    ('謝る', 'ayamaru', 'to apologize'),
    ('昼間', 'hiruma', 'daytime, during the day'),
    ('教育', 'kyouiku', 'education'),
    ('女性', 'josei', 'woman'),
    ('米', 'kome', 'uncooked rice'),
    ('邪魔', 'jama', 'hindrance, intrusion'),
    ('国際', 'kokusai', 'international'),
    ('隅', 'sumi', 'corner'),
    ('伺う', 'ukagau', 'humble form of 行く (いく), 聞く (きく) and 来る (くる)'),
    ('再来週', 'saraishuu', 'the week after next'),
    ('夢', 'yume', 'a dream'),
    ('喉', 'nodo', 'throat'),
    ('最近', 'saikin', 'recently, nowadays, in recent years, most recent, latest'),
    ('周り', 'mawari', 'surroundings'),
    ('歴史', 'rekishi', 'history'),
    ('不便', 'fuben', 'inconvenience'),
    ('血', 'chi', 'blood'),
    ('~続ける', '~tsuzukeru', 'to continue doing ~'),
    ('毛', 'ke', 'hair, fur'),
    ('ひどい', 'hidoi', 'terrible, awful, unfair, cruel'),
    ('例えば', 'tatoeba', 'for example, e.g.'),
    ('中々', 'nakanaka', 'very, considerably, quite'),
    ('随分', 'zuibun', 'extremely'),
    ('~やすい', '~yasui', 'easy to do ~'),
    ('押し入れ', 'oshiire', 'closet'),
    ('電灯', 'dentou', 'electric light'),
    ('叱る', 'shikaru', 'to scold'),
    ('サンダル', 'sandaru', 'sandal'),
    ('びっくりする', 'bikkurisuru', 'to be surprised'),
    ('うまい', 'umai', 'delicious; skillful; fortunate'),
    ('変える', 'kaeru', 'to change, to alter, to vary'),
    ('講堂', 'koudou', 'auditorium'),
    ('子', 'ko', 'child'),
    ('沸かす', 'wakasu', 'to boil'),
    ('レジ', 'reji', 'register'),
    ('しばらく', 'shibaraku', 'little while'),
    ('特に', 'tokuni', 'particularly'),
    ('空く', 'aku', 'to open, to become empty (vacant)'),
    ('計画', 'keikakusuru', 'plan, project, schedule'),
    ('通り', 'toori', '~ Street, ~ Avenue'),
    ('下着', 'shitagi', 'underwear'),
    ('経済', 'keizai', 'economics, finance, economy'),
    ('こう', 'kou', 'like this, this way'),
    ('是非', 'zehi', 'certainly, by all means; without fail'),
    ('裏', 'ura', 'reverse side, back'),
    ('為', 'tame', 'good, advantage, in order to'),
    ('おいでになる', 'oideninaru', '(hon.) to be'),
    ('変わる', 'kawaru', 'to change (v.i.), to be transformed, to vary'),
    ('以外', 'igai', 'other than, with the exception of, excepting'),
    ('済む', 'sumu', 'to finish, to end'),
    ('ハンバーグ', 'hambaagu', 'hamburger steak'),
    ('市', 'shi', 'city'),
    ('引き出し', 'hikidashi', 'drawer'),
    ('遊び', 'asobi', 'play'),
    ('支度', 'shitakusuru', 'preparation'),
    ('~始める', '~hajimeru', 'to start doing ~'),
    ('見える', 'mieru', 'to be visible; -- polite verb meaning 来る (くる) --'),
    ('十分', 'juubun', 'enough'),
    ('音', 'oto', 'sound, note'),
    ('きっと', 'kitto', 'surely, definitely, undoubtedly, certainly'),
    ('まず', 'mazu', 'first (of all), to start with'),
    ('遠く', 'tooku', 'far away, distant'),
    ('大体', 'daitai', 'approximately; in most cases; in general; to begin with (same as もともと)'),
    ('折れる', 'oreru', 'to break, to be folded, to give in; to turn (a corner)'),
    ('正しい', 'tadashii', 'correct'),
    ('輸入', 'yunyuu', 'import'),
    ('返事', 'henji', 'reply, answer'),
    ('都', 'to', 'metropolitan'),
    ('産業', 'sangyou', 'industry'),
    ('伝える', 'tsutaeru', 'to convey (a message); to tell, to report'),
    ('お金持ち', 'kanemochi okanemochi', 'rich person'),
    ('説明', 'setsumei', 'explanation'),
    ('島', 'shima', 'island'),
    ('道具', 'dougu', 'tool'),
    ('滑る', 'suberu', 'to slide, to slip'),
    ('それほど', 'sorehodo', 'to that degree; extent'),
    ('以上', 'ijou', 'more than; this is all'),
    ('~まま', '~mama', 'as it is'),
    ('特急', 'tokkyuu', 'limited express (train faster than an express)'),
    ('プレゼント', 'purezento', 'present, gift'),
    ('~(に) よると', '~(ni) yoruto', 'according to ~'),
    ('妻', 'tsuma', 'wife (humble)'),
    ('帰り', 'kaeri', 'return, coming back'),
    ('具合', 'guai', 'condition, state, health'),
    ('堅; 硬; 固い', 'katai', 'solid, hard, firm'),
    ('駐車場', 'chuushajou', 'parking lot'),
    ('スーツ', 'suutsu', 'suit'),
    ('危険', 'kiken', 'danger, risk, hazard'),
    ('髪', 'kami', 'hair'),
    ('天気予報', 'tenkiyohou', 'weather forecast'),
    ('彼女', 'kanojo', 'girlfriend; she'),
    ('間', 'aida', 'space, interval'),
    ('卒業', 'sotsugyou', 'graduation'),
    ('それで', 'sorede', 'and (conj.), thereupon, because of that'),
    ('枝', 'eda', 'branch, twig'),
    ('専門', 'semmon', 'major; speciality'),
    ('そろそろ', 'sorosoro', 'gradually, soon'),
    ('送る', 'okuru', 'to send, to dispatch'),
    ('あげる', 'ageru', 'to give'),
    ('騒ぐ', 'sawagu', 'to make noise, to clamor'),
    ('尋ねる', 'tazuneru', 'to inquire (same as 質問する)'),
    ('放送', 'housousuru', 'broadcasting'),
    ('政治', 'seiji', 'politics'),
    ('市民', 'shimin', 'citizen'),
    ('ファックス', 'fuakkusu', 'fax'),
    ('負ける', 'makeru', 'to lose (a game) (v.i.), to be defeated'),
    ('指輪', 'yubiwa', '(finger) ring'),
    ('田舎', 'inaka', 'rural, countryside'),
    ('見つける', 'mitsukeru', 'to discover, to find (v.t.)'),
    ('高校生', 'koukousei', 'high school student'),
    ('講義', 'kougi', 'a lecture'),
    ('そんなに', 'sonnani', 'so much, like that'),
    ('昼休み', 'hiruyasumi', 'lunch break, noon recess'),
    ('忘れ物', 'wasuremono', 'lost article, something forgotten'),
    ('下りる', 'oriru', 'to get down, to go; come down'),
    ('腕', 'ude', 'arm (in reference to body)'),
    ('訳', 'wake', 'reason; explanation'),
    ('承知', 'shouchisuru', 'consent, acceptance'),
    ('日記', 'nikki', 'diary, journal'),
    ('高校; 高等学校', 'koukou koutougakkou', 'high school; senior high school'),
    ('似る', 'niru', 'to resemble, to be similar'),
    ('~おわる', '~owaru', 'to finish doing ~'),
    ('暖房', 'dambou', 'heating'),
    ('留守', 'rusu', 'absence; not at home'),
    ('割合', 'wariai', 'rate, ratio, percentage'),
    ('寺', 'tera', 'Buddhist temple'),
    ('慣れる', 'nareru', 'to grow accustomed to'),
    ('普通', 'futsuu', 'common; usual'),
    ('手伝う', 'tetsudau', 'to help'),
    ('なるほど', 'naruhodo', 'I see; I now understand'),
    ('くださる', 'kudasaru', '(hon.) to give, to confer'),
    ('息子', 'musuko', '(humble) son'),
    ('お子さん', 'okosan', "(someone else's) child (polite)"),
    ('会場', 'kaijou', 'venue, meeting place'),
    ('笑う', 'warau', 'to laugh, to smile'),
    ('運ぶ', 'hakobu', 'to transport, to carry'),
    ('文学', 'bungaku', 'literature'),
    ('光', 'hikari', 'light'),
]

VOCAB_N3_EXTERNAL_DATA: list[tuple[str, str, str]] = [
    ('作法', 'sahou', 'manners, etiquette, propriety'),
    ('様々', 'samazama', 'varied, various'),
    ('冷ます', 'samasu', 'to cool, to let cool'),
    ('覚ます', 'samasu', 'to awaken'),
    ('冷める', 'sameru', 'to become cool, to wear off'),
    ('覚める', 'sameru', 'to wake, to wake up'),
    ('左右', 'sayuu', 'left and right; influence'),
    ('皿', 'sara', 'plate, dish'),
    ('更に', 'sarani', 'furthermore, moreover'),
    ('去る', 'saru', 'to leave, to go away'),
    ('猿', 'saru', 'monkey'),
    ('騒ぎ', 'sawagi', 'uproar, disturbance'),
    ('参加', 'sanka', 'participation'),
    ('参考', 'sankou', 'reference, consultation'),
    ('賛成', 'sansei', 'approval, agreement'),
    ('酸性', 'sansei', 'acidity'),
    ('酸素', 'sanso', 'oxygen'),
    ('氏', 'shi', 'family name, lineage'),
    ('詩', 'shi', 'poem; poetry'),
    ('幸せ', 'shiawase', 'happiness, blessing'),
    ('ジーンズ', 'jiinzu', 'jeans'),
    ('ジェット機', 'jiettoki', 'jet plane'),
    ('四角', 'shikaku', 'square'),
    ('直に', 'jikani', 'immediately, readily, directly'),
    ('しかも', 'shikamo', 'moreover, furthermore, besides, plus'),
    ('四季', 'shiki', 'four seasons'),
    ('直', 'jiki', 'immediately, soon, shortly'),
    ('時期', 'jiki', 'time, season, period'),
    ('支給', 'shikyuu', 'payment, allowance'),
    ('至急', 'shikyuu', 'urgent, pressing'),
    ('しきりに', 'shikirini', 'frequently, repeatedly, eagerly'),
    ('刺激', 'shigeki', 'stimulus, impetus, incentive'),
    ('資源', 'shigen', 'resources'),
    ('事件', 'jiken', 'event, affair, incident'),
    ('時刻', 'jikoku', 'time, hour'),
    ('自殺', 'jisatsu', 'suicide'),
    ('事実', 'jijitsu', 'fact, truth, reality'),
    ('支出', 'shishutsu', 'expenditure, expenses'),
    ('事情', 'jijou', 'circumstances, situation, reasons'),
    ('詩人', 'shijin', 'poet'),
    ('自身', 'jishin', 'oneself'),
    ('沈む', 'shizumu', 'to sink; to feel depressed'),
    ('自然', 'shizen', 'nature, spontaneous'),
    ('思想', 'shisou', 'thought, idea'),
    ('舌', 'shita', 'tongue'),
    ('次第', 'shidai', 'order; circumstances; immediate(ly)'),
    ('従う', 'shitagau', 'to abide (by the rules), to obey'),
    ('したがって', 'shitagatte', 'therefore, consequently'),
    ('親しい', 'shitashii', 'intimate, close (e.g., friend)'),
    ('質', 'shitsu', 'quality, nature (of person)'),
    ('失業', 'shitsugyou', 'unemployment'),
    ('湿気', 'shikke', 'moisture, humidity, dampness'),
    ('実験', 'jikken', 'lab work; experiment'),
    ('実現', 'jitsugen', 'implementation, materialization, realization'),
    ('実行', 'jikkou', 'practice, execution (e.g., program), realization'),
    ('実際', 'jissai', 'in fact; in actuality'),
    ('実施', 'jisshi', 'enforcement, carry out, operation'),
    ('湿度', 'shitsudo', 'humidity'),
    ('じっと', 'jitto', 'patiently, quietly'),
    ('実に', 'jitsuni', 'indeed, truly, surely'),
    ('実は', 'jitsuha', 'actually; in fact'),
    ('失望', 'shitsubou', 'disappointment, despair'),
    ('実力', 'jitsuryoku', 'ability; force'),
    ('支店', 'shiten', 'branch store (office)'),
    ('指導', 'shidou', 'leadership, guidance, coaching'),
    ('自動', 'jidou', 'automatic, self-motion'),
    ('児童', 'jidou', 'children, juvenile'),
    ('品', 'shina', 'thing, article, goods'),
    ('支配', 'shihai', 'rule, control, direction'),
    ('芝居', 'shibai', 'play, drama'),
    ('しばしば', 'shibashiba', 'often, again and again, frequently'),
    ('芝生', 'shibafu', 'lawn'),
    ('支払', 'shiharai', 'payment'),
    ('支払う', 'shiharau', 'to pay'),
    ('死亡', 'shibou', 'death'),
    ('資本', 'shihon', 'funds, capital'),
    ('姉妹', 'shimai', 'sisters'),
    ('しまった (かん)', 'shimatta (kan)', 'Damn it!'),
    ('自慢', 'jiman', 'pride, boast'),
    ('地味', 'jimi', 'quiet, plain, conservative'),
    ('示す', 'shimesu', 'to show, to indicate'),
    ('占める', 'shimeru', 'to take up; to account for'),
    ('湿る', 'shimeru', 'to be wet, to be damp'),
    ('下', 'shimo', 'under, below, beneath'),
    ('霜', 'shimo', 'frost'),
    ('借金', 'shakkin', 'debt, loan, liabilities'),
    ('しゃべる', 'shaberu', 'to talk, to chat, to chatter (same as 話す (はなす))'),
    ('週', 'shuu', 'week'),
    ('州', 'shuu', 'state, province'),
    ('銃', 'juu', 'gun'),
    ('周囲', 'shuui', 'surroundings, circumference, environs'),
    ('収穫', 'shuukaku', 'harvest, crop, ingathering'),
    ('宗教', 'shuukyou', 'religion'),
    ('重視', 'juushi', 'importance, stress'),
    ('就職', 'shuushoku', 'finding employment'),
    ('ジュース', 'juusu', 'juice, soft drink; deuce'),
    ('修正', 'shuusei', 'amendment, correction'),
    ('重体', 'juutai', 'seriously ill, critical state'),
    ('渋滞', 'juutai', 'congestion (e.g., traffic), delay'),
    ('重大', 'juudai', 'serious, important'),
    ('住宅', 'juutaku', 'resident, housing'),
    ('集団', 'shuudan', 'group, mass'),
    ('集中', 'shuuchuu', 'concentration, focusing the mind'),
    ('収入', 'shuunyuu', 'income, revenue'),
    ('住民', 'juumin', 'inhabitants, residents'),
    ('重要', 'juuyou', 'important, essential'),
    ('修理', 'shuuri', 'repairing, mending'),
    ('主義', 'shugi', 'doctrine, cause, principle'),
    ('宿泊', 'shukuhaku', 'lodging'),
    ('手術', 'shujutsu', 'surgical operation'),
    ('首相', 'shushou', 'Prime Minister'),
    ('手段', 'shudan', 'means, way, measure'),
    ('主張', 'shuchou', 'claim, insistence, assertion'),
    ('出場', 'shutsujou', 'participation'),
    ('出身', 'shusshin', 'come from'),
    ('出版', 'shuppan', 'publication'),
    ('首都', 'shuto', 'capital city'),
    ('主婦', 'shufu', 'housewife'),
    ('主要', 'shuyou', 'chief, main'),
    ('需要', 'juyou', 'demand'),
    ('種類', 'shurui', 'variety, kind'),
    ('順', 'jun', 'order, turn'),
    ('瞬間', 'shunkan', 'moment, second'),
    ('順調', 'junchou', 'doing well'),
    ('順番', 'jumban', 'turn (in line), order of things'),
    ('使用', 'shiyou', 'use (same as 使うこと (つかうこと)), application, employment, utilization'),
    ('小', 'shou', 'small'),
    ('章', 'shou', 'chapter, section; medal'),
    ('賞', 'shou', 'prize, award'),
    ('上', 'jou', 'first volume; superior quality; governmental'),
    ('障害', 'shougai', 'obstacle, impediment'),
    ('奨学金', 'shougakukin', 'scholarship'),
    ('乗客', 'joukyaku', 'passenger'),
    ('上京', 'joukyou', 'proceeding to the capital (Tokyo)'),
    ('状況', 'joukyou', 'state of affairs, situation'),
    ('条件', 'jouken', 'conditions, terms'),
    ('正午', 'shougo', 'noon, mid-day'),
    ('正直', 'shoujiki', 'honesty, integrity, frankness'),
    ('常識', 'joushiki', 'common sense'),
    ('少女', 'shoujo', 'young girl'),
    ('少々', 'shoushou', 'a little; short (time) (formal for 少し (すこし))'),
    ('症状', 'shoujou', 'symptoms, condition'),
    ('生じる', 'shoujiru', 'to occur, to arise, to be generated'),
    ('状態', 'joutai', 'condition, situation'),
    ('上達', 'joutatsu', 'improvement, advance'),
    ('冗談', 'joudan', 'a joke'),
    ('上等', 'joutou', 'first class, very good'),
    ('衝突', 'shoutotsu', 'collision, conflict'),
    ('商人', 'shounin', 'trader, shopkeeper, merchant'),
    ('承認', 'shounin', 'recognition, approval'),
    ('少年', 'shounen', 'boys, juveniles'),
    ('商売', 'shoubai', 'trade, business, commerce'),
    ('消費', 'shouhi', 'consumption, expenditure'),
    ('商品', 'shouhin', 'commodity, merchandise'),
    ('賞品', 'shouhin', 'prize, trophy'),
    ('消防', 'shoubou', 'fire fighting, fire department'),
    ('情報', 'jouhou', 'information, (military) intelligence'),
    ('証明', 'shoumei', 'proof, verification'),
    ('省略', 'shouryaku', 'omission, abbreviation, abridgment'),
    ('女王', 'joou', 'queen'),
    ('職', 'shoku', 'employment'),
    ('職業', 'shokugyou', 'occupation, business'),
    ('食卓', 'shokutaku', 'dining table'),
    ('食品', 'shokuhin', 'foodstuff'),
    ('植物', 'shokubutsu', 'plant, vegetation'),
    ('食物', 'shokumotsu', 'food, foodstuff'),
    ('食欲', 'shokuyoku', 'appetite (for food)'),
    ('食料', 'shokuryou', 'food'),
    ('食糧', 'shokuryou', 'provisions, rations'),
    ('書斎', 'shosai', 'study, den'),
    ('女子', 'joshi', 'woman, girl'),
    ('助手', 'joshu', 'helper, assistant'),
    ('徐々に', 'jojoni', 'slowly, little by little'),
    ('署名', 'shomei', 'signature'),
    ('書物', 'shomotsu', 'books'),
    ('女優', 'joyuu', 'actress'),
    ('処理', 'shori', 'processing, treatment, disposition'),
    ('書類', 'shorui', 'documents, official papers'),
    ('知らせ', 'shirase', 'notice'),
    ('尻', 'shiri', 'buttocks, bottom'),
    ('知合い', 'shiriai', 'acquaintance'),
    ('印', 'shirushi', 'mark; symbol; evidence'),
    ('城', 'shiro', 'castle'),
    ('進学', 'shingaku', 'going on to university'),
    ('神経', 'shinkei', 'nerve, sensitivity'),
    ('真剣', 'shinken', 'seriousness, earnestness'),
    ('信仰', 'shinkou', '(religious) faith, belief'),
    ('信号', 'shingou', 'traffic lights, signal, semaphore'),
    ('人工', 'jinkou', 'artificial, man made, human work,'),
    ('深刻', 'shinkoku', 'serious'),
    ('診察', 'shinsatsu', 'medical examination (of a patient)'),
    ('人種', 'jinshu', 'race (of people)'),
    ('信じる', 'shinjiru', 'to believe'),
    ('人生', 'jinsei', '(human) life (e.g., conception to death)'),
    ('親戚', 'shinseki', 'relative(s)'),
    ('新鮮', 'shinsen', 'fresh'),
    ('心臓', 'shinzou', 'heart'),
    ('身体', 'shintai', 'the body'),
    ('身長', 'shinchou', 'height (of body), stature'),
    ('慎重', 'shinchou', 'careful, prudent, cautious'),
    ('審判', 'shimpan', 'umpire, referee, judgment'),
    ('人物', 'jimbutsu', 'character, personality, talented man'),
    ('進歩', 'shimpo', 'improvement, progress, development'),
    ('親友', 'shinyuu', 'close friend, buddy'),
    ('信用', 'shinyou', 'confidence, dependence'),
    ('信頼', 'shinrai', 'reliance, trust, confidence'),
    ('心理', 'shinri', 'mentality'),
    ('人類', 'jinrui', 'mankind, humanity'),
    ('巣', 'su', 'nest, breeding place'),
    ('酢', 'su', 'vinegar'),
    ('図', 'zu', 'figure, drawing, illustration'),
    ('水準', 'suijun', 'level, standard'),
    ('推薦', 'suisen', 'recommendation'),
    ('スイッチ', 'suicchi', 'switch'),
    ('睡眠', 'suimin', 'sleep'),
    ('数', 'suu', 'number, figure'),
    ('数字', 'suuji', 'numeral, figure'),
    ('スープ', 'suupu', '(Western) soup'),
    ('末', 'sue', 'the end of, powder'),
    ('姿', 'sugata', 'figure, shape, appearance'),
    ('スキー', 'sukii', 'ski'),
    ('救う', 'sukuu', 'to rescue from, to help out of'),
    ('すくなくとも', 'sukunakutomo', 'at least'),
    ('優れる', 'sugureru', 'to surpass, to outstrip, to excel'),
    ('スケート', 'sukeeto', 'skate(s), skating'),
    ('スケジュール', 'sukejuuru', 'schedule'),
    ('少しも', 'sukoshimo', 'anything of, not one bit'),
    ('過ごす', 'sugosu', 'to pass, to spend (time)'),
    ('筋', 'suji', 'muscle, string, line'),
    ('進める', 'susumeru', 'to advance, to promote, to hasten'),
    ('勧める', 'susumeru', 'to urge (someone) to do (something), to recommend'),
    ('スター', 'sutaa', 'star'),
    ('スタイル', 'sutairu', 'style'),
    ('スタンド', 'sutando', 'stand'),
    ('頭痛', 'zutsuu', 'headache'),
    ('ずっと', 'zutto', 'for a long time; all the time; consecutively'),
    ('すっぱい', 'suppai', 'sour, acid'),
    ('すてき', 'suteki', 'lovely, great'),
    ('既に', 'sudeni', 'already (same as もう)'),
    ('すなわち', 'sunawachi', 'that is, namely, e.g.'),
    ('スピーチ', 'supiichi', 'speech'),
    ('全て', 'subete', 'all, the whole, entirely'),
    ('済ませる', 'sumaseru', 'to be finished'),
    ('角', 'sumi', 'corner'),
    ('墨', 'sumi', 'ink'),
    ('すみません (かん)', 'sumimasen (kan)', 'sorry, excuse me'),
    ('澄む', 'sumu', 'to clear (e.g., weather), to become transparent'),
    ('清む', 'sumu', 'to clear (e.g., weather), to become transparent'),
    ('刷る', 'suru', 'to print'),
    ('為る', 'suru', 'to do, to attempt'),
    ('鋭い', 'surudoi', 'pointed, sharp'),
    ('すれ違う', 'surechigau', 'to pass by one another'),
    ('ずれる', 'zureru', 'move, off the point'),
    ('正', 'sei', '(logical) true, regular'),
    ('生', 'sei', 'birth'),
    ('性', 'sei', 'sex, gender'),
    ('姓', 'sei', 'surname, family name'),
    ('所為', 'sei', 'cause, reason, fault'),
    ('税', 'zei', 'tax'),
    ('性格', 'seikaku', 'character, personality'),
    ('正確', 'seikaku', 'accurate, punctuality, exact'),
    ('世紀', 'seiki', 'century'),
    ('請求', 'seikyuu', 'claim, demand, request'),
    ('税金', 'zeikin', 'tax, duty'),
    ('清潔', 'seiketsu', 'clean'),
    ('制限', 'seigen', 'restriction, restraint, limitation'),
    ('成功', 'seikou', 'success, hit'),
    ('正式', 'seishiki', 'official, formal'),
    ('性質', 'seishitsu', 'nature, property, disposition'),
    ('精神', 'seishin', 'mind, soul, spirit'),
    ('成人', 'seijin', 'adult'),
    ('精々', 'seizei', 'at the most, at best'),
    ('成績', 'seiseki', 'grade (i.e., on a test), academic record'),
    ('製造', 'seizou', 'manufacture, production'),
    ('贅沢', 'zeitaku', 'luxury, extravagance'),
    ('成長', 'seichou', 'growth'),
    ('生長', 'seichou', 'growth'),
    ('制度', 'seido', 'system, institution'),
    ('青年', 'seinen', 'youth, young man'),
    ('生年月日', 'seinengappi', 'birth date'),
    ('製品', 'seihin', 'manufactured goods, finished goods'),
    ('政府', 'seifu', 'government, administration'),
    ('生物', 'seibutsu', 'living thing, organism'),
    ('生命', 'seimei', 'life'),
    ('整理', 'seiri', 'sorting, arrangement'),
    ('咳', 'seki', 'cough'),
    ('石炭', 'sekitan', 'coal'),
    ('責任', 'sekinin', 'duty, responsibility'),
    ('石油', 'sekiyu', 'oil, petroleum, kerosene'),
    ('世間', 'seken', 'world, society'),
    ('説', 'setsu', 'theory'),
    ('積極的', 'sekkyokuteki', 'positive, active, proactive'),
    ('設計', 'sekkei', 'plan, design'),
    ('絶対', 'zettai', 'definitely, without fail, absoluteness'),
    ('セット', 'setto', 'set'),
    ('愛', 'ai', 'love'),
    ('相変わらず', 'aikawarazu', 'as ever, as usual'),
    ('愛情', 'aijou', 'love, affection'),
    ('合図', 'aizu', 'sign, signal'),
    ('アイスクリーム', 'aisukuriimu', 'ice cream'),
    ('愛する', 'aisuru', 'to love'),
    ('相手', 'aite', 'partner; addressee; the person you are talking to'),
    ('あいにく', 'ainiku', 'unfortunately'),
    ('遭う', 'au', 'to meet, to encounter (undesirable nuance)'),
    ('アウト', 'auto', 'out'),
    ('明かり', 'akari', 'lamplight, light (in general)'),
    ('空き', 'aki', 'vacancy, opening, space'),
    ('明らか', 'akiraka', 'obvious, clear'),
    ('諦める', 'akirameru', 'to give up, to abandon'),
    ('飽きる', 'akiru', 'to get tired of, to lose interest in'),
    ('握手', 'akushu', 'handshake'),
    ('悪魔', 'akuma', 'devil, demon, evil spirit'),
    ('明ける', 'akeru', 'to dawn, to become daylight'),
    ('揚げる', 'ageru', 'to lift, to fry'),
    ('挙げる', 'ageru', 'to raise; to list, to cite'),
    ('預かる', 'azukaru', 'to keep (something) for (someone)'),
    ('預ける', 'azukeru', 'to give into custody, to deposit'),
    ('汗', 'ase', 'sweat, perspiration'),
    ('与える', 'ataeru', 'to give'),
    ('温かい', 'atatakai', 'warm'),
    ('暖まる', 'atatamaru', 'to warm up'),
    ('温まる', 'atatamaru', 'to warm oneself, to get warm'),
    ('暖める', 'atatameru', 'to warm (up to someone/something), to heat (up to someone/something)'),
    ('温める', 'atatameru', 'to warm, to heat'),
    ('辺り', 'atari', 'vicinity, nearby'),
    ('当たり前', 'atarimae', 'usual, common, obvious'),
    ('当たる', 'ataru', 'to be hit, to be successful'),
    ('あちこち', 'achikochi', 'here and there'),
    ('扱う', 'atsukau', 'to treat, to handle, to deal with'),
    ('集まり', 'atsumari', 'gathering, meeting, collection'),
    ('当てる', 'ateru', 'to hit; to apply to'),
    ('跡', 'ato', 'trace; remains; scar'),
    ('穴', 'ana', 'hole'),
    ('油', 'abura', 'oil'),
    ('脂', 'abura', 'fat'),
    ('誤り', 'ayamari', 'error'),
    ('粗', 'ara', 'defect, flaw, fault'),
    ('嵐', 'arashi', 'storm'),
    ('争う', 'arasou', 'to dispute, to argue, to fight'),
    ('新た', 'arata', 'new, fresh'),
    ('あらゆる', 'arayuru', 'all, every'),
    ('表す', 'arawasu', 'to express, to show'),
    ('現す', 'arawasu', 'to show, to appear, to reveal'),
    ('著す', 'arawasu', 'to write, to publish'),
    ('現れ', 'araware', 'expression, indication, sign'),
    ('現れる', 'arawareru', 'to appear (v.i.), to become visible; to express'),
    ('ありがとう', 'arigatou', 'Thank you'),
    ('在る; 有る', 'aru', 'to live, to be, to exist'),
    ('或', 'aru', 'a certain..., some...'),
    ('あるいは', 'aruiha', 'or, perhaps'),
]

VOCAB_N2_EXTERNAL_DATA: list[tuple[str, str, str]] = [
    ('〜 (まる) ごと', '(maru) goto', 'whole ~, all of ~'),
    ('(かさを~) さす', '(kasao~) sasu', 'to open; hold (an umbrella)'),
    ('〜(日本) 式', '~(nihon) shiki', 'custom,'),
    ('~位', '~i', '~th place'),
    ('~いち (にほんいち)', '~ichi (nihonichi)', 'No. 1 ~ (in)'),
    ('~園', '~en', '~ garden (especially man made)'),
    ('~おしまい (おわり)', '~oshimai (owari)', 'end up ~'),
    ('~日', '~ka', 'counter for days'),
    ('~下', '~ka', 'under ~'),
    ('~化', '~ka', 'action of making something'),
    ('~科', '~ka', 'family, group, course'),
    ('~歌', '~ka', 'song of ~'),
    ('~画', '~ga', 'picture, painting'),
    ('~外', '~gai', 'out of ~'),
    ('~難い', '~gatai', 'hard (difficult) to do ~'),
    ('~がち', '~gachi', 'tend to do ~'),
    ('~刊', '~kan', '~ issued (magazine, newspaper)'),
    ('~間', '~kan', 'between, during'),
    ('~巻', '~kan', 'volume'),
    ('~館', '~kan', '~ hall, ~ building'),
    ('~感', '~kan', 'feeling, sense, impression'),
    ('~期', '~ki', '~age, ~period'),
    ('~器', '~ki', 'device, equipment'),
    ('~機', '~ki', 'machine'),
    ('~気味', '~gimi', 'slightly ~'),
    ('~教', '~kyou', 'religion'),
    ('~行', '~gyou', 'line, row'),
    ('~業', '~gyou', 'type of business'),
    ('~きる', '~kiru', 'nevertheless, to carry through'),
    ('~切れ', '~kire', 'out of ~'),
    ('~口', '~kuchi', '~ opening; ~ entrance, ~ exit'),
    ('~家', '~ke', "~'s family, the house of ~"),
    ('~形', '~kei', 'shape of ~'),
    ('~系', '~kei', '~ system, ~ lineage, ~ group'),
    ('~圏', '~ken', 'bloc, sphere, area'),
    ('~校', '~kou', 'counter for school'),
    ('~港', '~kou', '~ port'),
    ('~号', '~gou', 'counter for magazine; the name of ship'),
    ('~国', '~koku', 'nation of ~'),
    ('~毎', '~goto', 'every ~, each ~'),
    ('~山', '~san', 'the name of mountain'),
    ('~産', '~san', 'made in ~'),
    ('~史', '~shi', 'history of ~'),
    ('~紙', '~shi', 'newspaper, type of paper'),
    ('~寺', '~ji', 'the name of temple'),
    ('~時間目', '~jikamme', '~th hour, ~th period'),
    ('~室', '~shitsu', 'counter for room'),
    ('~日', '~jitsu', 'day'),
    ('~車', '~sha', '~ car'),
    ('~者', '~sha', 'person'),
    ('~社', '~sha', 'counter for company'),
    ('~手', '~shu', '~ player, person who does ~'),
    ('~酒', '~shu', 'kind of alcohol'),
    ('~集', '~shuu', 'collection of ~'),
    ('~所', '~sho', 'place'),
    ('~所', '~jo', 'place'),
    ('~女', '~jo', 'count for sisters'),
    ('~省', '~shou', 'kind of ministry'),
    ('~商', '~shou', 'merchant, business'),
    ('~勝', '~shou', 'count for victory'),
    ('~条', '~jou', 'counter for article'),
    ('~場', '~jou', 'kind of field, ground'),
    ('~畳', '~jou', 'count for tatami, mat'),
    ('~色', '~shoku', 'kind of color'),
    ('~過ぎる', '~sugiru', 'too much ~'),
    ('~済', '~zumi', 'finished'),
    ('~席', '~seki', 'counter for seats'),
    ('~船', '~sen', 'counter for ships'),
    ('~戦', '~sen', 'counter for games, matches'),
    ('~前', '~zen', 'before ~'),
    ('~沿い', '~soi', 'along'),
    ('~艘', '~sou', 'counter for ships'),
    ('~足', '~soku', 'counter for shoes'),
    ('~だらけ', '~darake', 'be full of ~, be filled with ~'),
    ('~団', '~dan', 'group, corps, party'),
    ('~着', '~chaku', 'counter for clothes; finishing place'),
    ('~庁', '~chou', 'office, agency'),
    ('~兆', '~chou', 'trillion'),
    ('~長', '~chou', 'leader, head'),
    ('~帳', '~chou', '~ book, notebook'),
    ('~丁目', '~choume', '~ district (of a town; city, block)'),
    ('~通', '~tsuu', 'counter for letters'),
    ('~遣い', '~zukai', 'use of ~'),
    ('~付', '~tsuki', 'with ~'),
    ('~続く', '~tsuzuku', 'follow, continue, go on'),
    ('~辛い', '~zurai', 'hard to do ~'),
    ('~滴', '~teki', 'drop'),
    ('~点', '~ten', 'counter for scores'),
    ('~頭', '~tou', 'counter for animals'),
    ('~等', '~tou', 'level, place'),
    ('~島', '~tou', 'kind of islands'),
    ('~道', '~dou', 'kind of path, road'),
    ('~通り', '~toori', 'in accordance with ~; following ~; ~ street, ~ avenue'),
    ('~ところ', '~tokoro', 'about to do ~'),
    ('~内', '~nai', 'inside ~'),
    ('~年生', '~nensei', 'counter for school year'),
    ('~泊', '~haku', 'counter for staying (e.g., 2 nights)'),
    ('~発', '~hatsu', 'counter for bullets'),
    ('~番目', '~bamme', '~th'),
    ('~費', '~hi', 'cost of ~'),
    ('~病', '~byou', 'kind of disease'),
    ('~部', '~bu', '~ part'),
    ('~風', '~fuu', '~ style'),
    ('~振り', '~buri', 'after an interval of ~'),
    ('~遍', '~hen', 'time'),
    ('~弁', '~ben', 'speech, dialect'),
    ('~歩', '~ho', 'step, pace'),
    ('~ぽい', '~poi', '~ish'),
    ('~ほう (ひかく)', '~hou (hikaku)', '(in comparison)'),
    ('~みたい', '~mitai', 'looks like ~'),
    ('~向け', '~muke', 'for ~'),
    ('~名', '~mei', 'counter for people'),
    ('~もち', '~mochi', 'person who has ~'),
    ('~問', '~mon', 'counter for questions'),
    ('~夜', '~ya', 'counter for nights'),
    ('~等', '~ra', 'plural persons'),
    ('~流', '~ryuu', 'fashion, manner, way'),
    ('~料', '~ryou', 'fare, charge'),
    ('~領', '~ryou', 'territory'),
    ('~力', '~ryoku', 'power of ~'),
    ('~論', '~ron', 'theory'),
    ('~羽', '~wa', 'counter for rabbits; birds'),
    ('相変わらず', 'aikawarazu', 'as usual, as always, as before, as ever, still'),
    ('アイデア; アイディア', 'aidea aideia', 'idea'),
    ('あいまい', 'aimai', 'vague, ambiguous'),
    ('扇ぐ', 'aogu', 'to fan, to flap'),
    ('青白い', 'aojiroi', 'pale'),
    ('呆れる', 'akireru', 'to be shocked, to be appalled'),
    ('アクセント', 'akusento', 'accent'),
    ('あくび', 'akubi', 'yawn'),
    ('飽くまで', 'akumade', 'to the end, to the last, stubbornly'),
    ('明くる~', 'akuru~', 'next, following'),
    ('明け方', 'akegata', 'dawn'),
    ('憧れる', 'akogareru', 'to long for, to yearn after'),
    ('朝寝坊', 'asanebou', 'oversleeping, late riser'),
    ('足跡', 'ashiato', 'footprint'),
    ('足元', 'ashimoto', "at one's feet"),
    ('味わう', 'ajiwau', 'to taste, to savor'),
    ('預かる', 'azukaru', 'to keep in custody, to receive on deposit, to take charge of'),
    ('温まる', 'atatamaru', 'to warm oneself'),
    ('当たり前', 'atarimae', 'natural, reasonable, obvious, usual, common, ordinary, commonplace, the norm'),
    ('あちらこちら', 'achirakochira', 'here and there'),
    ('厚かましい', 'atsukamashii', 'impudent, shameless,'),
    ('圧縮', 'asshuku', 'compression, condensation, pressure'),
    ('宛名', 'atena', 'address, direction'),
    ('当てはまる', 'atehamaru', 'to be applicable, to come under (a category)'),
    ('当てはめる', 'atehameru', 'to apply, to adapt'),
    ('暴れる', 'abareru', 'to act violently, to rage'),
    ('脂', 'abura', 'fat, tallow, lard'),
    ('あぶる', 'aburu', 'to scorch, to roast'),
    ('あふれる', 'afureru', 'to flood, to overflow'),
    ('雨戸', 'amado', 'sliding storm door'),
    ('甘やかす', 'amayakasu', 'to pamper, to spoil'),
    ('余る', 'amaru', 'to be left over, to be in excess'),
    ('編み物', 'amimono', 'knitting'),
    ('あみもの', 'amimono', 'knitting, web'),
    ('編む', 'amu', 'to knit'),
    ('危うい', 'ayaui', 'dangerous, critical'),
    ('怪しい', 'ayashii', 'suspicious, dubious, doubtful'),
    ('荒い', 'arai', 'rough, rude, wild'),
    ('粗い', 'arai', 'coarse, rough'),
    ('粗筋', 'arasuji', 'outline, synopsis'),
    ('争う', 'arasou', 'to compete, to contest, to contend to quarrel, to argue, to dispute, to be at variance, to oppose'),
    ('改めて', 'aratamete', 'another time, again'),
    ('改める', 'aratameru', 'to change, to reform, to revise'),
    ('あらわす', 'arawasu', 'to write, to publish'),
    ('有難い', 'arigatai', 'grateful, thankful, appreciated'),
    ('あれこれ', 'arekore', 'one thing or another, this and that'),
    ('荒れる', 'areru', 'to be stormy, to be rough, to be ruined'),
    ('慌ただしい', 'awatadashii', 'busy, hurried'),
    ('慌てる', 'awateru', 'to become confused (disconcerted, disorganized), to be flustered, to panic, to hurry, to rush, to hasten'),
    ('安易', 'ani', 'easy-going'),
    ('案外', 'angai', 'unexpectedly, surprisingly'),
    ('アンテナ', 'antena', 'antenna'),
    ('言い出す', 'iidasu', 'to start talking, to suggest'),
    ('言い付ける', 'iitsukeru', 'to tell, to order'),
    ('意義', 'igi', 'meaning, significance'),
    ('生き生き', 'ikiiki', 'vividly, lively'),
    ('いきなり', 'ikinari', 'all of a sudden'),
    ('幾~', 'iku~', 'several ~'),
    ('育児', 'ikuji', 'childcare, nursing'),
    ('幾分', 'ikubun', 'somewhat'),
    ('生け花', 'ikebana', 'flower arrangement'),
    ('以後', 'igo', 'after this; from now on; hereafter'),
    ('イコール', 'ikooru', 'equal'),
    ('以降', 'ikou', 'on and after, hereafter'),
    ('勇ましい', 'isamashii', 'brave, valiant'),
    ('衣食住', 'ishokujuu', 'food, clothing and shelter'),
    ('いちいち', 'ichiichi', 'one by one, separately'),
    ('一応', 'ichiou', 'tentatively, for the time being'),
    ('一段と', 'ichidanto', 'by far, greater'),
    ('一流', 'ichiryuu', 'first class, leading'),
    ('一昨日', 'issakujitsu', 'day before yesterday'),
    ('一昨年', 'issakunen', 'year before last'),
    ('一斉', 'issei', 'simultaneous, all at once'),
    ('一旦', 'ittan', 'once, for a moment'),
    ('一定', 'ittei', 'fixed, settled, regular'),
    ('行っていらっしゃい', 'itteirasshai', 'have a nice day, see you'),
    ('いってきます', 'ittekimasu', "(Lit.) I'll go and come back, 'I'm going, see you later'"),
    ('いってまいります', 'ittemairimasu', "(Lit.) I'll go and come back, 'I'm going, see you later'"),
]

VOCAB_N1_EXTERNAL_DATA: list[tuple[str, str, str]] = [
    ('現像', 'genzou', 'developing (film)'),
    ('原則', 'gensoku', 'principle, general rule'),
    ('見地', 'kenchi', 'point of view'),
    ('現地', 'genchi', 'actual place, local'),
    ('限定', 'gentei', 'limit, restriction'),
    ('原点', 'genten', 'origin (coordinates, starting point)'),
    ('原典', 'genten', 'original, source'),
    ('原爆', 'gembaku', 'atomic bomb'),
    ('原文', 'gembun', 'the text, original'),
    ('厳密', 'gemmitsu', 'strict, close'),
    ('賢明', 'kemmei', 'wisdom, intelligence, prudence'),
    ('倹約', 'kenyaku', 'thrift, economy, frugality'),
    ('原油', 'genyu', 'crude oil'),
    ('兼用', 'kenyou', 'multi-use, combined use'),
    ('権力', 'kenryoku', '(political) power, authority, influence'),
    ('言論', 'genron', 'discussion, speech'),
    ('故~', 'ko~', 'deceased, late'),
    ('語彙', 'goi', 'vocabulary, glossary'),
    ('恋する', 'koisuru', 'to fall in love with, to love'),
    ('甲', 'kou', '1st in rank; shell'),
    ('~光', '~kou', 'light'),
    ('好意', 'koui', 'good will, favor, courtesy'),
    ('行為', 'koui', 'act, deed, conduct'),
    ('合意', 'goui', 'agreement, consent, mutual understanding'),
    ('工学', 'kougaku', 'engineering'),
    ('抗議', 'kougi', 'protest, objection'),
    ('合議', 'gougi', 'consultation, conference'),
    ('皇居', 'koukyo', 'Imperial Palace'),
    ('好況', 'koukyou', 'prosperous conditions, healthy economy'),
    ('鉱業', 'kougyou', 'mining industry'),
    ('興業', 'kougyou', 'starting a business; industry'),
    ('高原', 'kougen', 'tableland, plateau'),
    ('交互', 'kougo', 'mutual, reciprocal, alternate'),
    ('煌々と', 'koukouto', 'brightly'),
    ('考古学', 'koukogaku', 'archeology'),
    ('工作', 'kousaku', 'handicraft, maneuvering'),
    ('耕作', 'kousaku', 'cultivation, farming'),
    ('鉱山', 'kouzan', 'mine'),
    ('講習', 'koushuu', 'short course, training'),
    ('口述', 'koujutsu', 'verbal statement'),
    ('控除', 'koujo', 'subsidy, deduction'),
    ('交渉', 'koushou', 'negotiation'),
    ('高尚', 'koushou', 'high, noble, refined'),
    ('向上', 'koujou', 'rise, improvement, progress'),
    ('行進', 'koushin', 'march, parade'),
    ('香辛料', 'koushinryou', 'spices'),
    ('降水', 'kousui', 'rainfall, precipitation'),
    ('洪水', 'kouzui', 'flood'),
    ('合成', 'gousei', 'synthetic, mixed'),
    ('公然', 'kouzen', 'openly'),
]

GRAMMAR_PATTERNS_EXTERNAL_DATA: list[tuple[str, str, str]] = [
    ('〜は〜です', '〜 wa 〜 desu', 'X is Y (polite copula)'),
    ('〜は〜ではありません', '〜 wa 〜 dewa arimasen', 'X is not Y (polite negative)'),
    ('〜は〜ですか', '〜 wa 〜 desu ka', 'Is X Y? (polite question)'),
    ('〜は〜だ', '〜 wa 〜 da', 'X is Y (plain copula)'),
    ('〜があります', '〜 ga arimasu', 'There is/are 〜 (inanimate, polite)'),
    ('〜がいます', '〜 ga imasu', 'There is/are 〜 (animate, polite)'),
    ('〜は', '〜 wa', 'Topic marker particle'),
    ('〜が', '〜 ga', 'Subject marker / emphasis particle'),
    ('〜を', '〜 wo', 'Direct object marker particle'),
    ('〜に', '〜 ni', 'Location (existence) / direction / time particle'),
    ('〜で', '〜 de', 'Location (action) / means / method particle'),
    ('〜へ', '〜 e', 'Direction particle (toward)'),
    ('〜と', '〜 to', 'And (nouns) / with / quotation particle'),
    ('〜の', '〜 no', 'Possessive / noun-modifier particle'),
    ('〜も', '〜 mo', 'Also, too (inclusive particle)'),
    ('〜から', '〜 kara', 'From 〜 (starting point)'),
    ('〜まで', '〜 made', 'Until / up to 〜 (ending point)'),
    ('〜や〜など', '〜 ya 〜 nado', '〜 and 〜, etc. (non-exhaustive list)'),
    ('〜か〜', '〜 ka 〜', 'Or (between nouns)'),
    ('〜ます', '〜 masu', 'Polite present / future affirmative verb'),
    ('〜ません', '〜 masen', 'Polite present / future negative verb'),
    ('〜ました', '〜 mashita', 'Polite past affirmative verb'),
    ('〜ませんでした', '〜 masen deshita', 'Polite past negative verb'),
    ('〜ますか', '〜 masu ka', 'Polite verb question'),
    ('〜ましょう', '〜 mashou', "Let's 〜 / shall we 〜 (volitional)"),
    ('〜ましょうか', '〜 mashou ka', 'Shall I/we 〜? (offer/suggestion)'),
    ('〜てください', '〜 te kudasai', 'Please do 〜 (polite request)'),
    ('〜ています', '〜 te imasu', 'Is doing 〜 (ongoing action / state)'),
    ('〜てもいいですか', '〜 te mo ii desu ka', 'May I 〜? (asking permission)'),
    ('〜てはいけません', '〜 te wa ikemasen', 'Must not 〜 (prohibition)'),
    ('〜ないでください', '〜 nai de kudasai', "Please don't 〜"),
    ('〜い (present)', '〜 i (jisho-kei)', 'i-adjective dictionary form (e.g. たかい)'),
    ('〜くない', '〜 ku nai', 'i-adjective negative (e.g. たかくない)'),
    ('〜かった', '〜 katta', 'i-adjective past (e.g. たかかった)'),
    ('〜くなかった', '〜 ku nakatta', 'i-adjective past negative'),
    ('〜な (before noun)', '〜 na (noun)', 'na-adjective attributive form (e.g. きれいな)'),
    ('〜です (na-adj)', '〜 desu', 'na-adjective polite present (e.g. きれいです)'),
    ('〜ではありません (na-adj)', '〜 dewa arimasen', 'na-adjective polite negative'),
    ('なに/なん', 'nani/nan', 'What?'),
    ('どこ', 'doko', 'Where?'),
    ('だれ', 'dare', 'Who?'),
    ('いつ', 'itsu', 'When?'),
    ('どれ', 'dore', 'Which one?'),
    ('どの〜', 'dono 〜', 'Which 〜? (before noun)'),
    ('どんな〜', 'donna 〜', 'What kind of 〜?'),
    ('いくら', 'ikura', 'How much? (price)'),
    ('いくつ', 'ikutsu', 'How many? / How old?'),
    ('どうやって', 'dou yatte', 'How? By what means?'),
    ('なぜ/どうして', 'naze/doushite', 'Why?'),
    ('〜から (reason)', '〜 kara', 'Because 〜 (reason clause)'),
    ('〜が (contrast)', '〜 ga', 'But, however (mild contrast)'),
    ('〜けど/けれど', '〜 kedo/keredo', 'But, although (softer contrast)'),
    ('〜そして', 'soshite', 'And then, and also'),
    ('〜でも', 'demo', 'But, however (sentence-initial)'),
    ('〜をください', '〜 wo kudasai', 'Please give me 〜'),
    ('〜がほしい', '〜 ga hoshii', 'I want 〜 (noun)'),
    ('〜たい', '〜 tai', 'I want to 〜 (verb stem + たい)'),
    ('〜に行きます', '〜 ni ikimasu', 'Go to 〜 (destination)'),
    ('〜で行きます', '〜 de ikimasu', 'Go by 〜 (means of transport)'),
    ('どうぞよろしく', 'douzo yoroshiku', 'Nice to meet you / please treat me well'),
    ('〜はどうですか', '〜 wa dou desu ka', 'How about 〜? / How is 〜?'),
    ('〜はいくらですか', '〜 wa ikura desu ka', 'How much is 〜?'),
    ('〜はどこですか', '〜 wa doko desu ka', 'Where is 〜?'),
    ('〜はなんじですか', '〜 wa nanji desu ka', 'What time is 〜?'),
]

KANJI_N5_EXTERNAL_DATA: list[tuple[str, str, str]] = [
    ('一', 'ichi', 'one'),
    ('二', 'ni', 'two'),
    ('三', 'san', 'three'),
    ('四', 'yon/shi', 'four'),
    ('五', 'go', 'five'),
    ('六', 'roku', 'six'),
    ('七', 'nana/shichi', 'seven'),
    ('八', 'hachi', 'eight'),
    ('九', 'kyuu/ku', 'nine'),
    ('十', 'juu', 'ten'),
    ('百', 'hyaku', 'hundred'),
    ('千', 'sen', 'thousand'),
    ('万', 'man', 'ten thousand'),
    ('年', 'nen/toshi', 'year'),
    ('月', 'tsuki/gatsu', 'month, moon'),
    ('日', 'hi/nichi', 'day, sun, Japan'),
    ('時', 'toki/ji', 'time, hour'),
    ('分', 'fun/pun', 'minute, part'),
    ('半', 'han', 'half'),
    ('火', 'hi/ka', 'fire, Tuesday'),
    ('水', 'mizu/sui', 'water, Wednesday'),
    ('木', 'ki/moku', 'tree, Thursday'),
    ('金', 'kin/kane', 'gold, Friday, money'),
    ('土', 'tsuchi/do', 'earth, Saturday'),
    ('山', 'yama/san', 'mountain'),
    ('川', 'kawa/sen', 'river'),
    ('田', 'ta/den', 'rice field'),
    ('花', 'hana/ka', 'flower'),
    ('天', 'ten/ame', 'sky, heaven'),
    ('雨', 'ame/u', 'rain'),
    ('上', 'ue/jou', 'up, above'),
    ('下', 'shita/ka', 'down, below'),
    ('左', 'hidari', 'left'),
    ('右', 'migi', 'right'),
    ('前', 'mae/zen', 'front, before'),
    ('後', 'ushiro/go', 'back, after'),
    ('東', 'higashi/tou', 'east'),
    ('西', 'nishi/sei', 'west'),
    ('南', 'minami/nan', 'south'),
    ('北', 'kita/hoku', 'north'),
    ('中', 'naka/chuu', 'middle, inside'),
    ('外', 'soto/gai', 'outside'),
    ('内', 'uchi/nai', 'inside'),
    ('大', 'oo/dai', 'big, large'),
    ('小', 'chii/shou', 'small, little'),
    ('長', 'naga/chou', 'long, leader'),
    ('高', 'taka/kou', 'high, expensive'),
    ('古', 'furu/ko', 'old (things)'),
    ('新', 'atara/shin', 'new'),
    ('安', 'yasu/an', 'cheap, safe'),
    ('白', 'shiro/haku', 'white'),
    ('赤', 'aka/seki', 'red'),
    ('青', 'ao/sei', 'blue, green'),
    ('人', 'hito/jin', 'person'),
    ('子', 'ko/shi', 'child'),
    ('父', 'chichi/fu', 'father'),
    ('母', 'haha/bo', 'mother'),
    ('男', 'otoko/dan', 'man, male'),
    ('女', 'onna/jo', 'woman, female'),
    ('友', 'tomo/yuu', 'friend'),
    ('目', 'me/moku', 'eye'),
    ('口', 'kuchi/kou', 'mouth'),
    ('耳', 'mimi/ji', 'ear'),
    ('手', 'te/shu', 'hand'),
    ('足', 'ashi/soku', 'foot, leg'),
    ('力', 'chikara/ryoku', 'power, strength'),
    ('気', 'ki/ke', 'spirit, feeling, energy'),
    ('学', 'gaku/mana', 'study, learn'),
    ('校', 'kou', 'school'),
    ('生', 'sei/i', 'life, birth, student'),
    ('先', 'sen/saki', 'ahead, previous, teacher'),
    ('語', 'go/kata', 'language, word'),
    ('国', 'kuni/koku', 'country'),
    ('文', 'bun/fumi', 'sentence, writing'),
    ('字', 'ji/aza', 'character, letter'),
    ('本', 'hon/moto', 'book, origin, Japan'),
    ('見', 'mi/ken', 'see, look'),
    ('聞', 'ki/bun', 'hear, listen, ask'),
    ('食', 'ta/shoku', 'eat, food'),
    ('飲', 'no/in', 'drink'),
    ('来', 'ku/rai', 'come'),
    ('行', 'i/kou', 'go'),
    ('帰', 'kae/ki', 'return home'),
    ('書', 'ka/sho', 'write'),
    ('読', 'yo/doku', 'read'),
    ('立', 'ta/ritsu', 'stand'),
    ('入', 'i/nyuu', 'enter'),
    ('出', 'de/shutsu', 'exit, put out'),
    ('休', 'yasu/kyuu', 'rest, holiday'),
    ('電', 'den', 'electricity'),
    ('車', 'kuruma/sha', 'car, vehicle'),
]

KANJI_N4_EXTERNAL_DATA: list[tuple[str, str, str]] = [
    ('会', 'kai/a', 'meeting, association'),
    ('同', 'dou/onaji', 'same, agree'),
    ('事', 'ji/koto', 'matter, thing'),
    ('自', 'ji/mizu', 'self'),
    ('動', 'dou/ugo', 'move'),
    ('内', 'nai/uchi', 'inside'),
    ('時', 'ji/toki', 'time'),
    ('者', 'sha/mono', 'person'),
    ('作', 'saku/tsuku', 'make'),
    ('思', 'shi/omo', 'think'),
    ('住', 'ju/su', 'live, reside'),
    ('知', 'chi/shi', 'know'),
    ('場', 'jou/ba', 'place'),
    ('名', 'mei/na', 'name'),
    ('何', 'nan/nani', 'what'),
    ('体', 'tai/karada', 'body'),
    ('化', 'ka/baka', 'change'),
    ('主', 'shu/omo', 'main, master'),
    ('心', 'shin/kokoro', 'heart, mind'),
    ('対', 'tai', 'opposite, versus'),
    ('間', 'kan/aida', 'interval, between'),
    ('相', 'sou/ai', 'mutual, phase'),
    ('意', 'i', 'meaning, intention'),
    ('野', 'ya/no', 'field, plain'),
    ('開', 'kai/hira', 'open'),
    ('全', 'zen/sube', 'all, whole'),
    ('定', 'tei/sada', 'decide, fixed'),
    ('家', 'ka/ie', 'house, family'),
    ('方', 'hou/kata', 'direction, way'),
    ('代', 'dai/ka', 'generation, substitute'),
    ('道', 'dou/michi', 'road, way'),
    ('海', 'kai/umi', 'sea'),
    ('空', 'kuu/sora', 'sky'),
    ('店', 'ten/mise', 'shop'),
    ('駅', 'eki', 'station'),
    ('市', 'shi/ichi', 'city'),
    ('町', 'chou/machi', 'town'),
    ('村', 'son/mura', 'village'),
    ('県', 'ken', 'prefecture'),
    ('都', 'to/miyako', 'metropolis'),
    ('府', 'fu', 'urban prefecture'),
    ('近', 'kin/chika', 'near'),
    ('遠', 'en/too', 'far'),
    ('明', 'mei/aka', 'bright'),
    ('暗', 'an/kura', 'dark'),
    ('夜', 'ya/yoru', 'night'),
    ('朝', 'chou/asa', 'morning'),
    ('昼', 'chuu/hiru', 'noon'),
    ('教', 'kyou/oshi', 'teach'),
    ('強', 'kyou/tsuyo', 'strong'),
    ('弱', 'jaku/yowa', 'weak'),
    ('持', 'ji/mo', 'hold'),
    ('使', 'shi/tsuka', 'use'),
    ('待', 'tai/ma', 'wait'),
    ('走', 'sou/hashi', 'run'),
    ('歩', 'ho/aru', 'walk'),
    ('泳', 'ei/oyo', 'swim'),
    ('乗', 'jou/no', 'ride'),
    ('降', 'kou/o', 'descend'),
    ('着', 'chaku/ki', 'arrive'),
    ('死', 'shi/shi', 'die'),
    ('病', 'bou/yamai', 'sick'),
    ('院', 'in', 'institution'),
    ('薬', 'yaku/kusuri', 'medicine'),
    ('歌', 'ka/uta', 'song'),
    ('画', 'ga/kaku', 'picture'),
    ('界', 'kai', 'world'),
    ('問', 'mon/to', 'question'),
    ('答', 'tou/kota', 'answer'),
    ('仕', 'shi/tsuka', 'serve'),
]

KANJI_N3_EXTERNAL_DATA: list[tuple[str, str, str]] = [
    ('政', 'sei/matsuri', 'politics, government'),
    ('保', 'ho/tamo', 'protect, preserve'),
    ('所', 'sho/tokoro', 'place'),
    ('経', 'kei/he', 'manage, pass through'),
    ('応', 'ou', 'respond'),
    ('旅', 'ryo/tabi', 'trip, travel'),
    ('想', 'sou/omo', 'concept, think'),
    ('告', 'koku/tsu', 'announce'),
    ('調', 'chou/shira', 'investigate, tune'),
    ('連', 'ren/tsura', 'connect'),
    ('初', 'sho/hatsu', 'first, beginning'),
    ('続', 'zoku/tsuzu', 'continue'),
    ('少', 'shou/suku', 'few, little'),
    ('急', 'kyuu/iso', 'sudden, hurry'),
    ('守', 'shu/mamo', 'protect, obey'),
    ('起', 'ki/o', 'wake, occur'),
    ('転', 'ten/koro', 'turn, roll'),
    ('勝', 'shou/ka', 'win'),
    ('負', 'fu/ma', 'lose, bear'),
    ('務', 'mu/tsuto', 'duty'),
    ('命', 'mei/inochi', 'life, command'),
    ('算', 'san', 'calculate'),
    ('達', 'tatsu', 'attain'),
    ('術', 'jutsu', 'art, technique'),
    ('関', 'kan/seki', 'relation, barrier'),
    ('要', 'you/iru', 'need, require'),
    ('価', 'ka/atai', 'value, price'),
    ('差', 'sa/sasu', 'difference'),
    ('利', 'ri', 'benefit, advantage'),
    ('熱', 'netsu/atsu', 'heat, fever'),
    ('際', 'sai/kiwa', 'occasion'),
    ('察', 'satsu', 'guess'),
    ('提', 'tei/sage', 'propose'),
    ('案', 'an', 'plan'),
    ('導', 'dou/michi', 'guide'),
    ('設', 'setsu', 'establish'),
    ('備', 'bi/sona', 'prepare'),
    ('制', 'sei', 'system, control'),
    ('増', 'zou/fu', 'increase'),
    ('減', 'gen/he', 'decrease'),
    ('選', 'sen/era', 'choose'),
    ('残', 'zan/noko', 'remain'),
    ('断', 'dan/tatsu', 'decide, cut'),
    ('許', 'kyo/yuru', 'permit'),
    ('可', 'ka', 'possible'),
    ('否', 'hi', 'negate'),
    ('認', 'nin/mito', 'recognize'),
    ('識', 'shiki', 'discern'),
    ('在', 'zai/aru', 'exist'),
    ('非', 'hi', 'non-'),
    ('常', 'jou/tsune', 'usual'),
    ('必', 'hitsu/kanara', 'certain'),
    ('然', 'zen/nen', 'so'),
    ('果', 'ka/hata', 'result, fruit'),
    ('因', 'in/yori', 'cause'),
    ('議', 'gi', 'deliberation'),
    ('論', 'ron', 'argument'),
    ('検', 'ken', 'examine'),
    ('査', 'sa', 'investigate'),
    ('職', 'shoku', 'occupation'),
    ('接', 'setsu/tsu', 'connect'),
    ('客', 'kyaku', 'guest'),
    ('倍', 'bai', 'double'),
    ('税', 'zei', 'tax'),
    ('費', 'hi/tsui', 'expense'),
    ('給', 'kyuu/tama', 'supply'),
    ('管', 'kan/kuda', 'pipe, manage'),
    ('営', 'ei/itona', 'operate'),
    ('属', 'zoku', 'belong'),
    ('任', 'nin/maka', 'entrust'),
]

KANJI_N2_EXTERNAL_DATA: list[tuple[str, str, str]] = [
    ('率', 'ritsu', 'ratio, rate'),
    ('責', 'seki', 'responsibility'),
    ('略', 'ryaku', 'abbreviation, strategy'),
    ('範', 'han', 'scope, model'),
    ('模', 'mo', 'imitation, pattern'),
    ('精', 'sei', 'refined, spirit'),
    ('密', 'mitsu', 'dense, secret'),
    ('講', 'kou', 'lecture'),
    ('座', 'za', 'seat, sit'),
    ('援', 'en', 'aid, support'),
    ('競', 'kyou', 'compete'),
    ('争', 'sou/araso', 'conflict'),
    ('診', 'shin', 'diagnose'),
    ('療', 'ryou', 'medical treatment'),
    ('預', 'yo/azu', 'deposit, entrust'),
    ('貯', 'cho/takuwa', 'save, store'),
    ('測', 'soku/haka', 'measure, predict'),
    ('況', 'kyou', 'condition, situation'),
    ('資', 'shi', 'resource, capital'),
    ('源', 'gen/minamoto', 'source, origin'),
    ('穏', 'on/oda', 'calm'),
    ('緊', 'kin', 'tense, urgent'),
    ('圧', 'atsu', 'pressure'),
    ('縮', 'shuku/chiji', 'shrink'),
    ('拡', 'kaku', 'expand'),
    ('訳', 'yaku/wake', 'translate, reason'),
    ('省', 'sei/habu', 'ministry, omit'),
    ('境', 'kyou', 'boundary, situation'),
    ('補', 'ho/ogona', 'supplement'),
    ('総', 'sou', 'overall, total'),
    ('層', 'sou', 'layer'),
    ('盤', 'ban', 'board'),
    ('権', 'ken', 'right, authority'),
    ('益', 'eki/masu', 'benefit'),
    ('燃', 'nen/mo', 'burn'),
    ('衛', 'ei', 'defend'),
    ('警', 'kei', 'guard'),
    ('裁', 'sai/tachi', 'judge, cut'),
    ('判', 'han', 'judge'),
    ('署', 'sho', 'government office'),
    ('庁', 'chou', 'agency'),
    ('庶', 'sho', 'masses'),
    ('企', 'ki/kuda', 'plan'),
    ('幹', 'kan', 'main trunk'),
    ('即', 'soku', 'immediate'),
    ('諸', 'sho', 'various'),
    ('環', 'kan', 'ring, environment'),
    ('域', 'iki', 'region'),
    ('促', 'soku/unaga', 'prompt'),
    ('障', 'shou/sawa', 'obstacle'),
    ('危', 'ki/aya', 'danger'),
    ('刑', 'kei', 'punishment'),
    ('被', 'hi/kou', 'be subjected'),
    ('旧', 'kyuu/furu', 'old, former'),
    ('沿', 'en/soi', 'along'),
    ('違', 'i/chiga', 'differ'),
    ('択', 'taku', 'choose'),
    ('評', 'hyou', 'evaluate'),
    ('編', 'hen/amu', 'compile'),
    ('劇', 'geki', 'drama'),
    ('演', 'en/engi', 'perform'),
    ('需', 'ju', 'need, demand'),
    ('輸', 'yu', 'transport'),
    ('販', 'han', 'sell'),
    ('築', 'chiku/kizu', 'build'),
    ('操', 'sou/ayatsu', 'operate'),
    ('獲', 'kaku/e', 'acquire'),
    ('撃', 'geki/utsu', 'strike'),
    ('統', 'tou/sube', 'unify'),
    ('承', 'shou/uketa', 'consent'),
]

KANJI_N1_EXTERNAL_DATA: list[tuple[str, str, str]] = [
    ('顕', 'ken', 'appear, manifest'),
    ('諭', 'yu', 'instruct, persuade'),
    ('憂', 'yuu/ure', 'grief, worry'),
    ('曖', 'ai', 'vague'),
    ('昧', 'mai', 'dim, obscure'),
    ('鬱', 'utsu', 'depression'),
    ('償', 'shou/tsuguna', 'compensate'),
    ('懸', 'ken/kake', 'suspend, concern'),
    ('罰', 'batsu', 'punishment'),
    ('遵', 'jun', 'abide by'),
    ('擁', 'you', 'embrace, support'),
    ('護', 'go/mamoru', 'safeguard'),
    ('闘', 'tou/tataka', 'fight'),
    ('緩', 'kan/yuru', 'loosen'),
    ('隷', 'rei', 'servant, subordinate'),
    ('罷', 'hi', 'dismiss, quit'),
    ('顧', 'ko/kaeri', 'look back, consider'),
    ('諾', 'daku', 'consent'),
    ('賛', 'san', 'approve, praise'),
    ('璧', 'heki', 'flawless'),
    ('巧', 'kou/taku', 'skillful'),
    ('繊', 'sen', 'delicate, fine'),
    ('維', 'i', 'maintain'),
    ('羅', 'ra', 'gauze, net'),
    ('宰', 'sai', 'govern, manager'),
    ('亜', 'a', 'sub-, Asia'),
    ('赴', 'fu/omo', 'proceed toward'),
    ('該', 'gai', 'relevant'),
    ('勲', 'kun', 'distinguished service'),
    ('審', 'shin', 'judge, examine'),
    ('慮', 'ryo/omo', 'consideration'),
    ('賦', 'fu', 'levy'),
    ('謙', 'ken', 'humble'),
    ('顛', 'ten', 'overturn'),
    ('覆', 'fuku/oo', 'cover'),
    ('遷', 'sen/utsu', 'transition'),
    ('躍', 'yaku/odor', 'leap'),
    ('躊', 'chuu', 'hesitate'),
    ('躇', 'cho', 'hesitate'),
    ('冗', 'jou', 'redundant'),
    ('漠', 'baku', 'vague'),
    ('緻', 'chi', 'fine, precise'),
    ('飽', 'hou/a', 'bored'),
    ('脈', 'myaku', 'pulse'),
    ('潤', 'jun/uru', 'moisten'),
    ('崩', 'hou/kuzu', 'collapse'),
    ('醸', 'jou/kamo', 'brew'),
    ('撲', 'boku/utsu', 'slap'),
    ('廉', 'ren', 'honest'),
    ('峻', 'shun', 'steep'),
    ('敏', 'bin', 'agile, sensitive'),
    ('朴', 'boku', 'plain'),
    ('悠', 'yuu', 'distant'),
    ('僚', 'ryou', 'colleague'),
    ('謡', 'you', 'chant'),
    ('隠', 'in/kaku', 'hide'),
    ('遡', 'saku/saka', 'go upstream'),
    ('暫', 'zan/shibara', 'temporarily'),
    ('戴', 'tai/itadai', 'receive humbly'),
    ('憾', 'kan', 'regret'),
    ('懲', 'chou/korashi', 'chastise'),
    ('宵', 'shou/yoi', 'evening'),
    ('遂', 'sui/to', 'accomplish'),
    ('遜', 'son/heta', 'modest'),
    ('剰', 'jou', 'surplus'),
    ('頒', 'han', 'distribute'),
    ('藩', 'han', 'domain'),
    ('隅', 'gu/sumi', 'corner'),
    ('窮', 'kyuu/kiwa', 'be cornered'),
]
