"""Auto-generated external deck data. Do not edit by hand."""

# Generated from: data/external_sources/words_n5.csv
# Generated from: data/external_sources/conversational_n5.csv
# Generated from: data/external_sources/kanji_n5.csv
# Generated from: data/external_sources/kanji_n4.csv
# Generated from: data/external_sources/kanji_n3.csv
# Generated from: data/external_sources/kanji_n2.csv
# Generated from: data/external_sources/kanji_n1.csv

VOCAB_N5_EXTERNAL_DATA: list[tuple[str, str, str]] = [
    ('ひとつ', 'hitotsu', 'one (native count)'),
    ('ふたつ', 'futatsu', 'two (native count)'),
    ('みっつ', 'mittsu', 'three (native count)'),
    ('よっつ', 'yottsu', 'four (native count)'),
    ('いつつ', 'itsutsu', 'five (native count)'),
    ('いくつ', 'ikutsu', 'how many?'),
    ('きょう', 'kyou', 'today'),
    ('きのう', 'kinou', 'yesterday'),
    ('あした', 'ashita', 'tomorrow'),
    ('あさ', 'asa', 'morning'),
    ('ひる', 'hiru', 'noon, daytime'),
    ('よる', 'yoru', 'night, evening'),
    ('いま', 'ima', 'now'),
    ('まいにち', 'mainichi', 'every day'),
    ('まいあさ', 'maiasa', 'every morning'),
    ('ことし', 'kotoshi', 'this year'),
    ('らいねん', 'rainen', 'next year'),
    ('きょねん', 'kyonen', 'last year'),
    ('おとうさん', 'otousan', 'father (polite)'),
    ('おかあさん', 'okaasan', 'mother (polite)'),
    ('おにいさん', 'oniisan', 'older brother (polite)'),
    ('おねえさん', 'oneesan', 'older sister (polite)'),
    ('おとうと', 'otouto', 'younger brother'),
    ('いもうと', 'imouto', 'younger sister'),
    ('かぞく', 'kazoku', 'family'),
    ('ともだち', 'tomodachi', 'friend'),
    ('からだ', 'karada', 'body'),
    ('あたま', 'atama', 'head'),
    ('かお', 'kao', 'face'),
    ('はな', 'hana', 'nose'),
    ('かみ', 'kami', 'hair'),
    ('せ/せい', 'se/sei', 'height, stature'),
    ('ごはん', 'gohan', 'rice, meal'),
    ('みず', 'mizu', 'water'),
    ('おちゃ', 'ocha', 'green tea'),
    ('こうひー', 'koohii', 'coffee'),
    ('パン', 'pan', 'bread'),
    ('たまご', 'tamago', 'egg'),
    ('さかな', 'sakana', 'fish'),
    ('にく', 'niku', 'meat'),
    ('やさい', 'yasai', 'vegetables'),
    ('くだもの', 'kudamono', 'fruit'),
    ('のむ', 'nomu', 'to drink'),
    ('たべる', 'taberu', 'to eat'),
    ('つくる', 'tsukuru', 'to make, to cook'),
    ('がっこう', 'gakkou', 'school'),
    ('だいがく', 'daigaku', 'university'),
    ('せんせい', 'sensei', 'teacher'),
    ('がくせい', 'gakusei', 'student'),
    ('きょうしつ', 'kyoushitsu', 'classroom'),
    ('ほん', 'hon', 'book'),
    ('ノート', 'nooto', 'notebook'),
    ('えんぴつ', 'enpitsu', 'pencil'),
    ('かばん', 'kaban', 'bag'),
    ('よむ', 'yomu', 'to read'),
    ('かく', 'kaku', 'to write'),
    ('べんきょうする', 'benkyou suru', 'to study'),
    ('うち/いえ', 'uchi/ie', 'house, home'),
    ('へや', 'heya', 'room'),
    ('にわ', 'niwa', 'garden'),
    ('みせ', 'mise', 'shop, store'),
    ('えき', 'eki', 'train station'),
    ('びょういん', 'byouin', 'hospital'),
    ('こうえん', 'kouen', 'park'),
    ('としょかん', 'toshokan', 'library'),
    ('でんしゃ', 'densha', 'train'),
    ('バス', 'basu', 'bus'),
    ('じてんしゃ', 'jitensha', 'bicycle'),
    ('くるま', 'kuruma', 'car'),
    ('ひこうき', 'hikouki', 'airplane'),
    ('のる', 'noru', 'to ride, to get on'),
    ('おりる', 'oriru', 'to get off'),
    ('おおきい', 'ookii', 'big'),
    ('ちいさい', 'chiisai', 'small'),
    ('たかい', 'takai', 'expensive, tall'),
    ('やすい', 'yasui', 'cheap'),
    ('あたらしい', 'atarashii', 'new'),
    ('ふるい', 'furui', 'old (things)'),
    ('いい/よい', 'ii/yoi', 'good'),
    ('わるい', 'warui', 'bad'),
    ('おおい', 'ooi', 'many, much'),
    ('すくない', 'sukunai', 'few, little'),
    ('むずかしい', 'muzukashii', 'difficult'),
    ('やさしい', 'yasashii', 'easy, kind'),
    ('おもしろい', 'omoshiroi', 'interesting, fun'),
    ('つまらない', 'tsumaranai', 'boring'),
    ('あつい', 'atsui', 'hot'),
    ('さむい', 'samui', 'cold (weather)'),
    ('つめたい', 'tsumetai', 'cold (to touch/drink)'),
    ('みる', 'miru', 'to see, to watch'),
    ('きく', 'kiku', 'to hear, to listen, to ask'),
    ('いく', 'iku', 'to go'),
    ('くる', 'kuru', 'to come'),
    ('かえる', 'kaeru', 'to return home'),
    ('いる', 'iru', 'to be (animate)'),
    ('ある', 'aru', 'to be, to exist (inanimate)'),
    ('する', 'suru', 'to do'),
    ('おきる', 'okiru', 'to wake up, to get up'),
    ('ねる', 'neru', 'to sleep, to go to bed'),
    ('かう', 'kau', 'to buy'),
    ('うる', 'uru', 'to sell'),
    ('はなす', 'hanasu', 'to speak, to talk'),
    ('わかる', 'wakaru', 'to understand'),
    ('しる', 'shiru', 'to know'),
    ('もつ', 'motsu', 'to hold, to have'),
    ('あう', 'au', 'to meet'),
    ('まつ', 'matsu', 'to wait'),
    ('あそぶ', 'asobu', 'to play, to have fun'),
    ('はたらく', 'hataraku', 'to work'),
    ('ひと', 'hito', 'person'),
    ('こども', 'kodomo', 'child, children'),
    ('おとこのひと', 'otoko no hito', 'man'),
    ('おんなのひと', 'onna no hito', 'woman'),
    ('なまえ', 'namae', 'name'),
    ('くに', 'kuni', 'country'),
    ('ことば', 'kotoba', 'word, language'),
    ('にほんご', 'nihongo', 'Japanese language'),
    ('えいご', 'eigo', 'English language'),
    ('てんき', 'tenki', 'weather'),
    ('かぜ', 'kaze', 'wind'),
    ('あめ', 'ame', 'rain'),
    ('ゆき', 'yuki', 'snow'),
    ('そら', 'sora', 'sky'),
    ('うみ', 'umi', 'sea, ocean'),
    ('やま', 'yama', 'mountain'),
    ('かわ', 'kawa', 'river'),
    ('まち', 'machi', 'town, city'),
    ('とき', 'toki', 'time, moment'),
    ('もの', 'mono', 'thing (tangible)'),
    ('こと', 'koto', 'thing (abstract)'),
]

GRAMMAR_PATTERNS_EXTERNAL_DATA: list[tuple[str, str, str]] = [
    ('〜は〜です', '〜 wa 〜 desu', 'X is Y (polite copula)'),
    ('〜は〜ではありません', '〜 wa 〜 dewa arimasen', 'X is not Y (polite negative)'),
    ('〜は〜ですか', '〜 wa 〜 desu ka', 'Is X Y? (polite question)'),
    ('〜は〜だ', '〜 wa 〜 da', 'X is Y (plain copula)'),
    ('〜があります', '〜 ga arimasu', 'There is/are 〜 (inanimate, polite)'),
    ('〜がいます', '〜 ga imasu', 'There is/are 〜 (animate, polite)'),
    ('〜は', '〜 wa', 'Topic marker particle'),
    ('〜が', '〜 ga', 'Subject marker / emphasis particle'),
    ('〜を', '〜 wo', 'Direct object marker particle'),
    ('〜に', '〜 ni', 'Location (existence) / direction / time particle'),
    ('〜で', '〜 de', 'Location (action) / means / method particle'),
    ('〜へ', '〜 e', 'Direction particle (toward)'),
    ('〜と', '〜 to', 'And (nouns) / with / quotation particle'),
    ('〜の', '〜 no', 'Possessive / noun-modifier particle'),
    ('〜も', '〜 mo', 'Also, too (inclusive particle)'),
    ('〜から', '〜 kara', 'From 〜 (starting point)'),
    ('〜まで', '〜 made', 'Until / up to 〜 (ending point)'),
    ('〜や〜など', '〜 ya 〜 nado', '〜 and 〜, etc. (non-exhaustive list)'),
    ('〜か〜', '〜 ka 〜', 'Or (between nouns)'),
    ('〜ます', '〜 masu', 'Polite present / future affirmative verb'),
    ('〜ません', '〜 masen', 'Polite present / future negative verb'),
    ('〜ました', '〜 mashita', 'Polite past affirmative verb'),
    ('〜ませんでした', '〜 masen deshita', 'Polite past negative verb'),
    ('〜ますか', '〜 masu ka', 'Polite verb question'),
    ('〜ましょう', '〜 mashou', "Let's 〜 / shall we 〜 (volitional)"),
    ('〜ましょうか', '〜 mashou ka', 'Shall I/we 〜? (offer/suggestion)'),
    ('〜てください', '〜 te kudasai', 'Please do 〜 (polite request)'),
    ('〜ています', '〜 te imasu', 'Is doing 〜 (ongoing action / state)'),
    ('〜てもいいですか', '〜 te mo ii desu ka', 'May I 〜? (asking permission)'),
    ('〜てはいけません', '〜 te wa ikemasen', 'Must not 〜 (prohibition)'),
    ('〜ないでください', '〜 nai de kudasai', "Please don't 〜"),
    ('〜い (present)', '〜 i (jisho-kei)', 'i-adjective dictionary form (e.g. たかい)'),
    ('〜くない', '〜 ku nai', 'i-adjective negative (e.g. たかくない)'),
    ('〜かった', '〜 katta', 'i-adjective past (e.g. たかかった)'),
    ('〜くなかった', '〜 ku nakatta', 'i-adjective past negative'),
    ('〜な (before noun)', '〜 na (noun)', 'na-adjective attributive form (e.g. きれいな)'),
    ('〜です (na-adj)', '〜 desu', 'na-adjective polite present (e.g. きれいです)'),
    ('〜ではありません (na-adj)', '〜 dewa arimasen', 'na-adjective polite negative'),
    ('なに/なん', 'nani/nan', 'What?'),
    ('どこ', 'doko', 'Where?'),
    ('だれ', 'dare', 'Who?'),
    ('いつ', 'itsu', 'When?'),
    ('どれ', 'dore', 'Which one?'),
    ('どの〜', 'dono 〜', 'Which 〜? (before noun)'),
    ('どんな〜', 'donna 〜', 'What kind of 〜?'),
    ('いくら', 'ikura', 'How much? (price)'),
    ('いくつ', 'ikutsu', 'How many? / How old?'),
    ('どうやって', 'dou yatte', 'How? By what means?'),
    ('なぜ/どうして', 'naze/doushite', 'Why?'),
    ('〜から (reason)', '〜 kara', 'Because 〜 (reason clause)'),
    ('〜が (contrast)', '〜 ga', 'But, however (mild contrast)'),
    ('〜けど/けれど', '〜 kedo/keredo', 'But, although (softer contrast)'),
    ('〜そして', 'soshite', 'And then, and also'),
    ('〜でも', 'demo', 'But, however (sentence-initial)'),
    ('〜をください', '〜 wo kudasai', 'Please give me 〜'),
    ('〜がほしい', '〜 ga hoshii', 'I want 〜 (noun)'),
    ('〜たい', '〜 tai', 'I want to 〜 (verb stem + たい)'),
    ('〜に行きます', '〜 ni ikimasu', 'Go to 〜 (destination)'),
    ('〜で行きます', '〜 de ikimasu', 'Go by 〜 (means of transport)'),
    ('どうぞよろしく', 'douzo yoroshiku', 'Nice to meet you / please treat me well'),
    ('〜はどうですか', '〜 wa dou desu ka', 'How about 〜? / How is 〜?'),
    ('〜はいくらですか', '〜 wa ikura desu ka', 'How much is 〜?'),
    ('〜はどこですか', '〜 wa doko desu ka', 'Where is 〜?'),
    ('〜はなんじですか', '〜 wa nanji desu ka', 'What time is 〜?'),
]

KANJI_N5_EXTERNAL_DATA: list[tuple[str, str, str]] = [
    ('一', 'ichi', 'one'),
    ('二', 'ni', 'two'),
    ('三', 'san', 'three'),
    ('四', 'yon/shi', 'four'),
    ('五', 'go', 'five'),
    ('六', 'roku', 'six'),
    ('七', 'nana/shichi', 'seven'),
    ('八', 'hachi', 'eight'),
    ('九', 'kyuu/ku', 'nine'),
    ('十', 'juu', 'ten'),
    ('百', 'hyaku', 'hundred'),
    ('千', 'sen', 'thousand'),
    ('万', 'man', 'ten thousand'),
    ('年', 'nen/toshi', 'year'),
    ('月', 'tsuki/gatsu', 'month, moon'),
    ('日', 'hi/nichi', 'day, sun, Japan'),
    ('時', 'toki/ji', 'time, hour'),
    ('分', 'fun/pun', 'minute, part'),
    ('半', 'han', 'half'),
    ('火', 'hi/ka', 'fire, Tuesday'),
    ('水', 'mizu/sui', 'water, Wednesday'),
    ('木', 'ki/moku', 'tree, Thursday'),
    ('金', 'kin/kane', 'gold, Friday, money'),
    ('土', 'tsuchi/do', 'earth, Saturday'),
    ('山', 'yama/san', 'mountain'),
    ('川', 'kawa/sen', 'river'),
    ('田', 'ta/den', 'rice field'),
    ('花', 'hana/ka', 'flower'),
    ('天', 'ten/ame', 'sky, heaven'),
    ('雨', 'ame/u', 'rain'),
    ('上', 'ue/jou', 'up, above'),
    ('下', 'shita/ka', 'down, below'),
    ('左', 'hidari', 'left'),
    ('右', 'migi', 'right'),
    ('前', 'mae/zen', 'front, before'),
    ('後', 'ushiro/go', 'back, after'),
    ('東', 'higashi/tou', 'east'),
    ('西', 'nishi/sei', 'west'),
    ('南', 'minami/nan', 'south'),
    ('北', 'kita/hoku', 'north'),
    ('中', 'naka/chuu', 'middle, inside'),
    ('外', 'soto/gai', 'outside'),
    ('内', 'uchi/nai', 'inside'),
    ('大', 'oo/dai', 'big, large'),
    ('小', 'chii/shou', 'small, little'),
    ('長', 'naga/chou', 'long, leader'),
    ('高', 'taka/kou', 'high, expensive'),
    ('古', 'furu/ko', 'old (things)'),
    ('新', 'atara/shin', 'new'),
    ('安', 'yasu/an', 'cheap, safe'),
    ('白', 'shiro/haku', 'white'),
    ('赤', 'aka/seki', 'red'),
    ('青', 'ao/sei', 'blue, green'),
    ('人', 'hito/jin', 'person'),
    ('子', 'ko/shi', 'child'),
    ('父', 'chichi/fu', 'father'),
    ('母', 'haha/bo', 'mother'),
    ('男', 'otoko/dan', 'man, male'),
    ('女', 'onna/jo', 'woman, female'),
    ('友', 'tomo/yuu', 'friend'),
    ('目', 'me/moku', 'eye'),
    ('口', 'kuchi/kou', 'mouth'),
    ('耳', 'mimi/ji', 'ear'),
    ('手', 'te/shu', 'hand'),
    ('足', 'ashi/soku', 'foot, leg'),
    ('力', 'chikara/ryoku', 'power, strength'),
    ('気', 'ki/ke', 'spirit, feeling, energy'),
    ('学', 'gaku/mana', 'study, learn'),
    ('校', 'kou', 'school'),
    ('生', 'sei/i', 'life, birth, student'),
    ('先', 'sen/saki', 'ahead, previous, teacher'),
    ('語', 'go/kata', 'language, word'),
    ('国', 'kuni/koku', 'country'),
    ('文', 'bun/fumi', 'sentence, writing'),
    ('字', 'ji/aza', 'character, letter'),
    ('本', 'hon/moto', 'book, origin, Japan'),
    ('見', 'mi/ken', 'see, look'),
    ('聞', 'ki/bun', 'hear, listen, ask'),
    ('食', 'ta/shoku', 'eat, food'),
    ('飲', 'no/in', 'drink'),
    ('来', 'ku/rai', 'come'),
    ('行', 'i/kou', 'go'),
    ('帰', 'kae/ki', 'return home'),
    ('書', 'ka/sho', 'write'),
    ('読', 'yo/doku', 'read'),
    ('立', 'ta/ritsu', 'stand'),
    ('入', 'i/nyuu', 'enter'),
    ('出', 'de/shutsu', 'exit, put out'),
    ('休', 'yasu/kyuu', 'rest, holiday'),
    ('電', 'den', 'electricity'),
    ('車', 'kuruma/sha', 'car, vehicle'),
]

KANJI_N4_EXTERNAL_DATA: list[tuple[str, str, str]] = [
    ('会', 'kai/a', 'meeting, association'),
    ('同', 'dou/onaji', 'same, agree'),
    ('事', 'ji/koto', 'matter, thing'),
    ('自', 'ji/mizu', 'self'),
    ('動', 'dou/ugo', 'move'),
    ('内', 'nai/uchi', 'inside'),
    ('時', 'ji/toki', 'time'),
    ('者', 'sha/mono', 'person'),
    ('作', 'saku/tsuku', 'make'),
    ('思', 'shi/omo', 'think'),
    ('住', 'ju/su', 'live, reside'),
    ('知', 'chi/shi', 'know'),
    ('場', 'jou/ba', 'place'),
    ('名', 'mei/na', 'name'),
    ('何', 'nan/nani', 'what'),
    ('体', 'tai/karada', 'body'),
    ('化', 'ka/baka', 'change'),
    ('主', 'shu/omo', 'main, master'),
    ('心', 'shin/kokoro', 'heart, mind'),
    ('対', 'tai', 'opposite, versus'),
    ('間', 'kan/aida', 'interval, between'),
    ('相', 'sou/ai', 'mutual, phase'),
    ('意', 'i', 'meaning, intention'),
    ('野', 'ya/no', 'field, plain'),
    ('開', 'kai/hira', 'open'),
    ('全', 'zen/sube', 'all, whole'),
    ('定', 'tei/sada', 'decide, fixed'),
    ('家', 'ka/ie', 'house, family'),
    ('方', 'hou/kata', 'direction, way'),
    ('代', 'dai/ka', 'generation, substitute'),
    ('道', 'dou/michi', 'road, way'),
    ('海', 'kai/umi', 'sea'),
    ('空', 'kuu/sora', 'sky'),
    ('店', 'ten/mise', 'shop'),
    ('駅', 'eki', 'station'),
    ('市', 'shi/ichi', 'city'),
    ('町', 'chou/machi', 'town'),
    ('村', 'son/mura', 'village'),
    ('県', 'ken', 'prefecture'),
    ('都', 'to/miyako', 'metropolis'),
    ('府', 'fu', 'urban prefecture'),
    ('近', 'kin/chika', 'near'),
    ('遠', 'en/too', 'far'),
    ('明', 'mei/aka', 'bright'),
    ('暗', 'an/kura', 'dark'),
    ('夜', 'ya/yoru', 'night'),
    ('朝', 'chou/asa', 'morning'),
    ('昼', 'chuu/hiru', 'noon'),
    ('教', 'kyou/oshi', 'teach'),
    ('強', 'kyou/tsuyo', 'strong'),
    ('弱', 'jaku/yowa', 'weak'),
    ('持', 'ji/mo', 'hold'),
    ('使', 'shi/tsuka', 'use'),
    ('待', 'tai/ma', 'wait'),
    ('走', 'sou/hashi', 'run'),
    ('歩', 'ho/aru', 'walk'),
    ('泳', 'ei/oyo', 'swim'),
    ('乗', 'jou/no', 'ride'),
    ('降', 'kou/o', 'descend'),
    ('着', 'chaku/ki', 'arrive'),
    ('死', 'shi/shi', 'die'),
    ('病', 'bou/yamai', 'sick'),
    ('院', 'in', 'institution'),
    ('薬', 'yaku/kusuri', 'medicine'),
    ('歌', 'ka/uta', 'song'),
    ('画', 'ga/kaku', 'picture'),
    ('界', 'kai', 'world'),
    ('問', 'mon/to', 'question'),
    ('答', 'tou/kota', 'answer'),
    ('仕', 'shi/tsuka', 'serve'),
]

KANJI_N3_EXTERNAL_DATA: list[tuple[str, str, str]] = [
    ('政', 'sei/matsuri', 'politics, government'),
    ('保', 'ho/tamo', 'protect, preserve'),
    ('所', 'sho/tokoro', 'place'),
    ('経', 'kei/he', 'manage, pass through'),
    ('応', 'ou', 'respond'),
    ('旅', 'ryo/tabi', 'trip, travel'),
    ('想', 'sou/omo', 'concept, think'),
    ('告', 'koku/tsu', 'announce'),
    ('調', 'chou/shira', 'investigate, tune'),
    ('連', 'ren/tsura', 'connect'),
    ('初', 'sho/hatsu', 'first, beginning'),
    ('続', 'zoku/tsuzu', 'continue'),
    ('少', 'shou/suku', 'few, little'),
    ('急', 'kyuu/iso', 'sudden, hurry'),
    ('守', 'shu/mamo', 'protect, obey'),
    ('起', 'ki/o', 'wake, occur'),
    ('転', 'ten/koro', 'turn, roll'),
    ('勝', 'shou/ka', 'win'),
    ('負', 'fu/ma', 'lose, bear'),
    ('務', 'mu/tsuto', 'duty'),
    ('命', 'mei/inochi', 'life, command'),
    ('算', 'san', 'calculate'),
    ('達', 'tatsu', 'attain'),
    ('術', 'jutsu', 'art, technique'),
    ('関', 'kan/seki', 'relation, barrier'),
    ('要', 'you/iru', 'need, require'),
    ('価', 'ka/atai', 'value, price'),
    ('差', 'sa/sasu', 'difference'),
    ('利', 'ri', 'benefit, advantage'),
    ('熱', 'netsu/atsu', 'heat, fever'),
    ('際', 'sai/kiwa', 'occasion'),
    ('察', 'satsu', 'guess'),
    ('提', 'tei/sage', 'propose'),
    ('案', 'an', 'plan'),
    ('導', 'dou/michi', 'guide'),
    ('設', 'setsu', 'establish'),
    ('備', 'bi/sona', 'prepare'),
    ('制', 'sei', 'system, control'),
    ('増', 'zou/fu', 'increase'),
    ('減', 'gen/he', 'decrease'),
    ('選', 'sen/era', 'choose'),
    ('残', 'zan/noko', 'remain'),
    ('断', 'dan/tatsu', 'decide, cut'),
    ('許', 'kyo/yuru', 'permit'),
    ('可', 'ka', 'possible'),
    ('否', 'hi', 'negate'),
    ('認', 'nin/mito', 'recognize'),
    ('識', 'shiki', 'discern'),
    ('在', 'zai/aru', 'exist'),
    ('非', 'hi', 'non-'),
    ('常', 'jou/tsune', 'usual'),
    ('必', 'hitsu/kanara', 'certain'),
    ('然', 'zen/nen', 'so'),
    ('果', 'ka/hata', 'result, fruit'),
    ('因', 'in/yori', 'cause'),
    ('議', 'gi', 'deliberation'),
    ('論', 'ron', 'argument'),
    ('検', 'ken', 'examine'),
    ('査', 'sa', 'investigate'),
    ('職', 'shoku', 'occupation'),
    ('接', 'setsu/tsu', 'connect'),
    ('客', 'kyaku', 'guest'),
    ('倍', 'bai', 'double'),
    ('税', 'zei', 'tax'),
    ('費', 'hi/tsui', 'expense'),
    ('給', 'kyuu/tama', 'supply'),
    ('管', 'kan/kuda', 'pipe, manage'),
    ('営', 'ei/itona', 'operate'),
    ('属', 'zoku', 'belong'),
    ('任', 'nin/maka', 'entrust'),
]

KANJI_N2_EXTERNAL_DATA: list[tuple[str, str, str]] = [
    ('率', 'ritsu', 'ratio, rate'),
    ('責', 'seki', 'responsibility'),
    ('略', 'ryaku', 'abbreviation, strategy'),
    ('範', 'han', 'scope, model'),
    ('模', 'mo', 'imitation, pattern'),
    ('精', 'sei', 'refined, spirit'),
    ('密', 'mitsu', 'dense, secret'),
    ('講', 'kou', 'lecture'),
    ('座', 'za', 'seat, sit'),
    ('援', 'en', 'aid, support'),
    ('競', 'kyou', 'compete'),
    ('争', 'sou/araso', 'conflict'),
    ('診', 'shin', 'diagnose'),
    ('療', 'ryou', 'medical treatment'),
    ('預', 'yo/azu', 'deposit, entrust'),
    ('貯', 'cho/takuwa', 'save, store'),
    ('測', 'soku/haka', 'measure, predict'),
    ('況', 'kyou', 'condition, situation'),
    ('資', 'shi', 'resource, capital'),
    ('源', 'gen/minamoto', 'source, origin'),
    ('穏', 'on/oda', 'calm'),
    ('緊', 'kin', 'tense, urgent'),
    ('圧', 'atsu', 'pressure'),
    ('縮', 'shuku/chiji', 'shrink'),
    ('拡', 'kaku', 'expand'),
    ('訳', 'yaku/wake', 'translate, reason'),
    ('省', 'sei/habu', 'ministry, omit'),
    ('境', 'kyou', 'boundary, situation'),
    ('補', 'ho/ogona', 'supplement'),
    ('総', 'sou', 'overall, total'),
    ('層', 'sou', 'layer'),
    ('盤', 'ban', 'board'),
    ('権', 'ken', 'right, authority'),
    ('益', 'eki/masu', 'benefit'),
    ('燃', 'nen/mo', 'burn'),
    ('衛', 'ei', 'defend'),
    ('警', 'kei', 'guard'),
    ('裁', 'sai/tachi', 'judge, cut'),
    ('判', 'han', 'judge'),
    ('署', 'sho', 'government office'),
    ('庁', 'chou', 'agency'),
    ('庶', 'sho', 'masses'),
    ('企', 'ki/kuda', 'plan'),
    ('幹', 'kan', 'main trunk'),
    ('即', 'soku', 'immediate'),
    ('諸', 'sho', 'various'),
    ('環', 'kan', 'ring, environment'),
    ('域', 'iki', 'region'),
    ('促', 'soku/unaga', 'prompt'),
    ('障', 'shou/sawa', 'obstacle'),
    ('危', 'ki/aya', 'danger'),
    ('刑', 'kei', 'punishment'),
    ('被', 'hi/kou', 'be subjected'),
    ('旧', 'kyuu/furu', 'old, former'),
    ('沿', 'en/soi', 'along'),
    ('違', 'i/chiga', 'differ'),
    ('択', 'taku', 'choose'),
    ('評', 'hyou', 'evaluate'),
    ('編', 'hen/amu', 'compile'),
    ('劇', 'geki', 'drama'),
    ('演', 'en/engi', 'perform'),
    ('需', 'ju', 'need, demand'),
    ('輸', 'yu', 'transport'),
    ('販', 'han', 'sell'),
    ('築', 'chiku/kizu', 'build'),
    ('操', 'sou/ayatsu', 'operate'),
    ('獲', 'kaku/e', 'acquire'),
    ('撃', 'geki/utsu', 'strike'),
    ('統', 'tou/sube', 'unify'),
    ('承', 'shou/uketa', 'consent'),
]

KANJI_N1_EXTERNAL_DATA: list[tuple[str, str, str]] = [
    ('顕', 'ken', 'appear, manifest'),
    ('諭', 'yu', 'instruct, persuade'),
    ('憂', 'yuu/ure', 'grief, worry'),
    ('曖', 'ai', 'vague'),
    ('昧', 'mai', 'dim, obscure'),
    ('鬱', 'utsu', 'depression'),
    ('償', 'shou/tsuguna', 'compensate'),
    ('懸', 'ken/kake', 'suspend, concern'),
    ('罰', 'batsu', 'punishment'),
    ('遵', 'jun', 'abide by'),
    ('擁', 'you', 'embrace, support'),
    ('護', 'go/mamoru', 'safeguard'),
    ('闘', 'tou/tataka', 'fight'),
    ('緩', 'kan/yuru', 'loosen'),
    ('隷', 'rei', 'servant, subordinate'),
    ('罷', 'hi', 'dismiss, quit'),
    ('顧', 'ko/kaeri', 'look back, consider'),
    ('諾', 'daku', 'consent'),
    ('賛', 'san', 'approve, praise'),
    ('璧', 'heki', 'flawless'),
    ('巧', 'kou/taku', 'skillful'),
    ('繊', 'sen', 'delicate, fine'),
    ('維', 'i', 'maintain'),
    ('羅', 'ra', 'gauze, net'),
    ('宰', 'sai', 'govern, manager'),
    ('亜', 'a', 'sub-, Asia'),
    ('赴', 'fu/omo', 'proceed toward'),
    ('該', 'gai', 'relevant'),
    ('勲', 'kun', 'distinguished service'),
    ('審', 'shin', 'judge, examine'),
    ('慮', 'ryo/omo', 'consideration'),
    ('賦', 'fu', 'levy'),
    ('謙', 'ken', 'humble'),
    ('顛', 'ten', 'overturn'),
    ('覆', 'fuku/oo', 'cover'),
    ('遷', 'sen/utsu', 'transition'),
    ('躍', 'yaku/odor', 'leap'),
    ('躊', 'chuu', 'hesitate'),
    ('躇', 'cho', 'hesitate'),
    ('冗', 'jou', 'redundant'),
    ('漠', 'baku', 'vague'),
    ('緻', 'chi', 'fine, precise'),
    ('飽', 'hou/a', 'bored'),
    ('脈', 'myaku', 'pulse'),
    ('潤', 'jun/uru', 'moisten'),
    ('崩', 'hou/kuzu', 'collapse'),
    ('醸', 'jou/kamo', 'brew'),
    ('撲', 'boku/utsu', 'slap'),
    ('廉', 'ren', 'honest'),
    ('峻', 'shun', 'steep'),
    ('敏', 'bin', 'agile, sensitive'),
    ('朴', 'boku', 'plain'),
    ('悠', 'yuu', 'distant'),
    ('僚', 'ryou', 'colleague'),
    ('謡', 'you', 'chant'),
    ('隠', 'in/kaku', 'hide'),
    ('遡', 'saku/saka', 'go upstream'),
    ('暫', 'zan/shibara', 'temporarily'),
    ('戴', 'tai/itadai', 'receive humbly'),
    ('憾', 'kan', 'regret'),
    ('懲', 'chou/korashi', 'chastise'),
    ('宵', 'shou/yoi', 'evening'),
    ('遂', 'sui/to', 'accomplish'),
    ('遜', 'son/heta', 'modest'),
    ('剰', 'jou', 'surplus'),
    ('頒', 'han', 'distribute'),
    ('藩', 'han', 'domain'),
    ('隅', 'gu/sumi', 'corner'),
    ('窮', 'kyuu/kiwa', 'be cornered'),
]
