// Conjugation drill round construction (issue #22).
//
// Sits beside grammarRound.ts and follows the same contract: return null when
// this card cannot produce a round, and buildRoundWithBridge falls back to an
// ordinary round for it. That fallback is what lets the drill live in the
// per-section minigame catalog at all — SCRIPT_MINIGAMES is keyed on the six
// ScriptKey sections, not deck slugs, so a noun card will be handed to this
// builder and simply has to decline.

import type { RoundDictionaryNote, RoundState, ScriptDeck } from '../../types'
import { CONJUGATION_DRILLABLE_WORDS } from '../../generated/conjugationIndex'

/**
 * Whether a card can produce a conjugation round.
 *
 * Exact, not a guess: the index is generated by running the bridge's own
 * classifier over every built-in vocabulary deck. A spelling heuristic was
 * wrong in precisely the place it mattered — おやすみなさい and ごめんなさい end
 * in い without being adjectives, and in a 15-card themed block those two *were*
 * the whole pool, so every round fell back to another mode.
 *
 * Used both to build the session pool and to lock the mode in the menu when a
 * block has nothing to drill, so the two can never disagree.
 */
export function isConjugationDrillCandidate(character: string): boolean {
  return CONJUGATION_DRILLABLE_WORDS.has(character.trim())
}

/** Below this many eligible cards, a pool is topped up from the parent deck. */
export const CONJUGATION_POOL_FLOOR = 8

/**
 * Eligible cards from `blockCards`, extended from `deckCards` when the block
 * alone would repeat the same handful of words all session.
 *
 * Block cards keep their leading position, so a themed block still studies its
 * own content first — the top-up only fills the tail.
 */
export function buildConjugationPool(
  blockCards: ScriptDeck['cards'],
  deckCards: ScriptDeck['cards'],
  floor: number = CONJUGATION_POOL_FLOOR,
): ScriptDeck['cards'] {
  const pool = blockCards.filter((card) => isConjugationDrillCandidate(card.character))
  if (pool.length >= floor) return pool

  const seen = new Set(pool.map((card) => card.character))
  const available = deckCards.filter(
    (card) => !seen.has(card.character) && isConjugationDrillCandidate(card.character),
  )
  // Decks are ordered by reading, so taking the first N would hand every thin
  // block the same あ-row cluster (会う, 青い, 赤い, 明るい…). Striding spreads
  // the sample across the deck while staying deterministic for tests.
  const needed = Math.min(floor - pool.length, available.length)
  const stride = Math.max(1, Math.floor(available.length / needed))
  for (let taken = 0; taken < needed; taken += 1) {
    pool.push(available[(taken * stride) % available.length])
  }
  return pool
}

export async function buildConjugationDrillRound(
  card: ScriptDeck['cards'][number],
  options: {
    curriculumStage: 1 | 2 | 3
    surprisePrompt: boolean
    surpriseLabel: string
    promptSeed: number
    dictionarySeedQuery: string | null
    dictionaryNote: RoundDictionaryNote | null
  },
): Promise<RoundState | null> {
  const {
    curriculumStage,
    surprisePrompt,
    surpriseLabel,
    promptSeed,
    dictionarySeedQuery,
    dictionaryNote,
  } = options

  const getDrillData = window.jplearnDesktop?.getConjugationDrillData
  if (!getDrillData) return null

  const word = card.character?.trim()
  if (!word) return null

  let response
  try {
    response = await getDrillData({
      word,
      stage: curriculumStage,
      seed: promptSeed,
    })
  } catch {
    // The bridge rejects anything it cannot classify — a noun, an inflected
    // form, a kana-only る-verb of ambiguous class. Not an error worth
    // surfacing: the card just gets a different minigame this round.
    return null
  }

  const data = response?.data
  if (!data || typeof data.expected !== 'string' || data.expected.length === 0) return null

  const accepted = Array.isArray(data.accepted)
    ? data.accepted.filter((entry): entry is string => typeof entry === 'string' && entry.trim().length > 0)
    : []
  if (accepted.length === 0) return null

  const formLabel = typeof data.form_label === 'string' ? data.form_label : 'requested form'
  const ruleHint = typeof data.rule_hint === 'string' && data.rule_hint.length > 0
    ? data.rule_hint
    : null

  return {
    cardId: card.id,
    mode: 'conjugation_drill',
    audioText: data.expected,
    exampleSentenceAudioText: null,
    surprisePrompt,
    curriculumStage,
    chapterNumber: null,
    chapterLabel: null,
    hintText: ruleHint,
    dictionarySeedQuery,
    dictionaryNote,
    promptLabel: surprisePrompt ? surpriseLabel : `Write the ${formLabel} of this word.`,
    focusText: data.word,
    answer: data.expected,
    answerDisplay: data.expected_reading && data.expected_reading !== data.expected
      ? `${data.expected}（${data.expected_reading}）`
      : data.expected,
    acceptedAnswers: accepted,
    options: [],
  }
}
